// Common category sprites — everyday objects, tools, furniture, containers
export const COMMON_SPRITES = [
  { id: 'golden_key', name: 'Golden Key', category: 'common', tags: ['key', 'lock', 'unlock', 'door', 'secret', 'access', 'metal', 'golden', 'ornate'], emoji: '🔑' },
  { id: 'lantern', name: 'Lantern', category: 'common', tags: ['lantern', 'light', 'lamp', 'flame', 'fire', 'glow', 'iron', 'warm', 'illuminate'], emoji: '🏮' },
  { id: 'candle', name: 'Candle', category: 'common', tags: ['candle', 'light', 'flame', 'wax', 'wick', 'glow', 'warm', 'melt'], emoji: '🕯️' },
  { id: 'torch', name: 'Torch', category: 'common', tags: ['torch', 'fire', 'flame', 'light', 'burn', 'cave', 'medieval', 'wooden'], emoji: '🔦' },
  { id: 'mirror', name: 'Mirror', category: 'common', tags: ['mirror', 'reflection', 'glass', 'vanity', 'silver', 'frame', 'look'], emoji: '🪞' },
  { id: 'clock', name: 'Clock', category: 'common', tags: ['clock', 'time', 'hour', 'tick', 'gears', 'face', 'wall', 'pendulum'], emoji: '🕰️' },
  { id: 'bell', name: 'Bell', category: 'common', tags: ['bell', 'ring', 'chime', 'sound', 'brass', 'church', 'alarm', 'toll'], emoji: '🔔' },
  { id: 'rope', name: 'Rope', category: 'common', tags: ['rope', 'cord', 'tie', 'knot', 'bind', 'hemp', 'coil', 'climb'], emoji: '🪢' },
  { id: 'bucket', name: 'Bucket', category: 'common', tags: ['bucket', 'pail', 'water', 'carry', 'well', 'wooden', 'metal'], emoji: '🪣' },
  { id: 'barrel', name: 'Barrel', category: 'common', tags: ['barrel', 'cask', 'wine', 'storage', 'wooden', 'tavern', 'ale'], emoji: '🛢️' },
  { id: 'chair', name: 'Chair', category: 'common', tags: ['chair', 'seat', 'sit', 'furniture', 'wooden', 'rest', 'throne'], emoji: '🪑' },
  { id: 'table', name: 'Table', category: 'common', tags: ['table', 'furniture', 'surface', 'wooden', 'dining', 'flat', 'work'], emoji: '🪵' },
  { id: 'bed', name: 'Bed', category: 'common', tags: ['bed', 'sleep', 'rest', 'furniture', 'pillow', 'blanket', 'dream'], emoji: '🛏️' },
  { id: 'pillow', name: 'Pillow', category: 'common', tags: ['pillow', 'soft', 'sleep', 'cushion', 'rest', 'feather', 'comfort'], emoji: '💤' },
  { id: 'broom', name: 'Broom', category: 'common', tags: ['broom', 'sweep', 'clean', 'bristle', 'wooden', 'witch', 'dust'], emoji: '🧹' },
  { id: 'cauldron', name: 'Cauldron', category: 'common', tags: ['cauldron', 'pot', 'brew', 'iron', 'witch', 'cook', 'bubble', 'stew'], emoji: '🫕' },
  { id: 'shield', name: 'Shield', category: 'common', tags: ['shield', 'defend', 'protect', 'armor', 'knight', 'metal', 'crest'], emoji: '🛡️' },
  { id: 'helmet', name: 'Helmet', category: 'common', tags: ['helmet', 'armor', 'head', 'knight', 'warrior', 'metal', 'visor'], emoji: '⛑️' },
  { id: 'wheel', name: 'Wheel', category: 'common', tags: ['wheel', 'spin', 'round', 'cart', 'wagon', 'wooden', 'spoke'], emoji: '☸️' },
  { id: 'ladder', name: 'Ladder', category: 'common', tags: ['ladder', 'climb', 'rung', 'height', 'wooden', 'ascend', 'step'], emoji: '🪜' },
  { id: 'curtain', name: 'Curtain', category: 'common', tags: ['curtain', 'drape', 'fabric', 'window', 'cover', 'hide', 'velvet'], emoji: '🎭' },
  { id: 'chandelier', name: 'Chandelier', category: 'common', tags: ['chandelier', 'light', 'crystal', 'ceiling', 'elegant', 'candle', 'hang'], emoji: '✨' },
  { id: 'bench', name: 'Bench', category: 'common', tags: ['bench', 'seat', 'sit', 'park', 'wooden', 'rest', 'long'], emoji: '🪑' },
  { id: 'basket', name: 'Basket', category: 'common', tags: ['basket', 'weave', 'carry', 'wicker', 'container', 'gather', 'picnic'], emoji: '🧺' },
  { id: 'jug', name: 'Jug', category: 'common', tags: ['jug', 'pitcher', 'pour', 'water', 'ceramic', 'clay', 'vessel'], emoji: '🫗' },
  { id: 'bowl', name: 'Bowl', category: 'common', tags: ['bowl', 'dish', 'food', 'round', 'ceramic', 'soup', 'serve'], emoji: '🥣' },
  { id: 'plate', name: 'Plate', category: 'common', tags: ['plate', 'dish', 'food', 'round', 'flat', 'ceramic', 'dinner'], emoji: '🍽️' },
  { id: 'cup', name: 'Cup', category: 'common', tags: ['cup', 'drink', 'mug', 'tea', 'coffee', 'ceramic', 'vessel'], emoji: '☕' },
  { id: 'fork_utensil', name: 'Fork', category: 'common', tags: ['fork', 'utensil', 'eat', 'prong', 'metal', 'dinner', 'silver'], emoji: '🍴' },
  { id: 'spoon', name: 'Spoon', category: 'common', tags: ['spoon', 'utensil', 'eat', 'scoop', 'metal', 'silver', 'stir'], emoji: '🥄' },
  { id: 'pan', name: 'Pan', category: 'common', tags: ['pan', 'cook', 'fry', 'iron', 'skillet', 'kitchen', 'handle'], emoji: '🍳' },
  { id: 'kettle', name: 'Kettle', category: 'common', tags: ['kettle', 'boil', 'water', 'tea', 'steam', 'copper', 'whistle'], emoji: '🫖' },
  { id: 'teapot', name: 'Teapot', category: 'common', tags: ['teapot', 'tea', 'pour', 'ceramic', 'brew', 'spout', 'warm'], emoji: '🫖' },
  { id: 'vase', name: 'Vase', category: 'common', tags: ['vase', 'flower', 'ceramic', 'pottery', 'decorative', 'vessel', 'elegant'], emoji: '🏺' },
  { id: 'pot', name: 'Pot', category: 'common', tags: ['pot', 'cook', 'boil', 'clay', 'ceramic', 'container', 'stew'], emoji: '🍯' },
  { id: 'mortar_pestle', name: 'Mortar & Pestle', category: 'common', tags: ['mortar', 'pestle', 'grind', 'crush', 'herb', 'alchemy', 'stone'], emoji: '⚗️' },
  { id: 'scale', name: 'Scale', category: 'common', tags: ['scale', 'weigh', 'balance', 'measure', 'justice', 'brass', 'pan'], emoji: '⚖️' },
  { id: 'chain', name: 'Chain', category: 'common', tags: ['chain', 'link', 'metal', 'iron', 'bind', 'connect', 'strong'], emoji: '⛓️' },
  { id: 'lock', name: 'Lock', category: 'common', tags: ['lock', 'key', 'secure', 'closed', 'metal', 'latch', 'protect'], emoji: '🔒' },
  { id: 'padlock', name: 'Padlock', category: 'common', tags: ['padlock', 'lock', 'secure', 'key', 'metal', 'shackle', 'guard'], emoji: '🔐' },
  { id: 'hammer', name: 'Hammer', category: 'common', tags: ['hammer', 'tool', 'hit', 'nail', 'forge', 'iron', 'build'], emoji: '🔨' },
  { id: 'axe', name: 'Axe', category: 'common', tags: ['axe', 'chop', 'wood', 'blade', 'tool', 'lumber', 'split'], emoji: '🪓' },
  { id: 'saw', name: 'Saw', category: 'common', tags: ['saw', 'cut', 'wood', 'blade', 'teeth', 'tool', 'lumber'], emoji: '🪚' },
  { id: 'wrench', name: 'Wrench', category: 'common', tags: ['wrench', 'tool', 'turn', 'bolt', 'metal', 'fix', 'mechanic'], emoji: '🔧' },
  { id: 'pliers', name: 'Pliers', category: 'common', tags: ['pliers', 'tool', 'grip', 'squeeze', 'metal', 'wire', 'bend'], emoji: '🔧' },
  { id: 'shovel', name: 'Shovel', category: 'common', tags: ['shovel', 'dig', 'earth', 'dirt', 'tool', 'garden', 'metal'], emoji: '🪏' },
  { id: 'pickaxe', name: 'Pickaxe', category: 'common', tags: ['pickaxe', 'mine', 'rock', 'dig', 'tool', 'metal', 'ore'], emoji: '⛏️' },
  { id: 'rake', name: 'Rake', category: 'common', tags: ['rake', 'garden', 'leaves', 'tool', 'gather', 'wooden', 'tines'], emoji: '🍂' },
  { id: 'chisel', name: 'Chisel', category: 'common', tags: ['chisel', 'carve', 'stone', 'tool', 'sculpt', 'metal', 'sharp'], emoji: '🪛' },
  { id: 'knife_utensil', name: 'Knife', category: 'common', tags: ['knife', 'cut', 'blade', 'sharp', 'kitchen', 'slice', 'steel'], emoji: '🔪' },
  { id: 'blanket', name: 'Blanket', category: 'common', tags: ['blanket', 'warm', 'cover', 'soft', 'fabric', 'wrap', 'cozy'], emoji: '🛋️' },
  { id: 'bookshelf', name: 'Bookshelf', category: 'common', tags: ['bookshelf', 'books', 'shelf', 'library', 'wooden', 'read', 'organize'], emoji: '📚' },
  { id: 'cabinet', name: 'Cabinet', category: 'common', tags: ['cabinet', 'storage', 'door', 'wooden', 'cupboard', 'shelf', 'organize'], emoji: '🗄️' },
  { id: 'desk', name: 'Desk', category: 'common', tags: ['desk', 'work', 'write', 'furniture', 'wooden', 'office', 'study'], emoji: '🖥️' },
  { id: 'crate', name: 'Crate', category: 'common', tags: ['crate', 'box', 'wooden', 'cargo', 'ship', 'storage', 'pack'], emoji: '📦' },
  { id: 'sack', name: 'Sack', category: 'common', tags: ['sack', 'bag', 'carry', 'cloth', 'grain', 'burlap', 'heavy'], emoji: '👝' },
  { id: 'urn', name: 'Urn', category: 'common', tags: ['urn', 'vase', 'ceramic', 'ancient', 'ashes', 'decorative', 'clay'], emoji: '⚱️' },
  { id: 'oil_lamp', name: 'Oil Lamp', category: 'common', tags: ['oil', 'lamp', 'light', 'flame', 'wick', 'brass', 'glow'], emoji: '🛢️' },
  { id: 'umbrella', name: 'Umbrella', category: 'common', tags: ['umbrella', 'rain', 'cover', 'shield', 'weather', 'handle', 'open'], emoji: '☂️' },
  { id: 'fan', name: 'Fan', category: 'common', tags: ['fan', 'cool', 'breeze', 'fold', 'wave', 'paper', 'wind'], emoji: '🪭' },
  { id: 'comb', name: 'Comb', category: 'common', tags: ['comb', 'hair', 'groom', 'teeth', 'brush', 'style', 'wooden'], emoji: '💇' },
  { id: 'brush', name: 'Brush', category: 'common', tags: ['brush', 'paint', 'bristle', 'art', 'stroke', 'clean', 'wooden'], emoji: '🖌️' },
  { id: 'needle_thread', name: 'Needle & Thread', category: 'common', tags: ['needle', 'thread', 'sew', 'stitch', 'fabric', 'tailor', 'mend'], emoji: '🪡' },
  { id: 'anvil', name: 'Anvil', category: 'common', tags: ['anvil', 'forge', 'iron', 'smith', 'hammer', 'metal', 'heavy'], emoji: '⚒️' },
  { id: 'net', name: 'Net', category: 'common', tags: ['net', 'catch', 'fish', 'trap', 'weave', 'rope', 'mesh'], emoji: '🥅' },
  { id: 'anchor', name: 'Anchor', category: 'common', tags: ['anchor', 'ship', 'sea', 'heavy', 'iron', 'dock', 'moor'], emoji: '⚓' },
  { id: 'flag', name: 'Flag', category: 'common', tags: ['flag', 'banner', 'wave', 'pole', 'symbol', 'cloth', 'wind'], emoji: '🚩' },
  { id: 'fence', name: 'Fence', category: 'common', tags: ['fence', 'barrier', 'wooden', 'yard', 'boundary', 'post', 'rail'], emoji: '🏗️' },
  { id: 'gate', name: 'Gate', category: 'common', tags: ['gate', 'entrance', 'iron', 'open', 'close', 'arch', 'passage'], emoji: '🚪' },
  { id: 'well', name: 'Well', category: 'common', tags: ['well', 'water', 'deep', 'stone', 'bucket', 'wish', 'draw'], emoji: '🕳️' },
  { id: 'pillar', name: 'Pillar', category: 'common', tags: ['pillar', 'column', 'stone', 'support', 'marble', 'temple', 'tall'], emoji: '🏛️' },
  { id: 'statue', name: 'Statue', category: 'common', tags: ['statue', 'sculpture', 'stone', 'figure', 'marble', 'art', 'monument'], emoji: '🗿' },
  { id: 'weathervane', name: 'Weathervane', category: 'common', tags: ['weathervane', 'wind', 'direction', 'rooster', 'roof', 'metal', 'spin'], emoji: '🐓' },
  { id: 'pipe_smoking', name: 'Pipe', category: 'common', tags: ['pipe', 'smoke', 'tobacco', 'wooden', 'bowl', 'stem', 'puff'], emoji: '🪈' },
  { id: 'gear', name: 'Gear', category: 'common', tags: ['gear', 'cog', 'machine', 'metal', 'teeth', 'turn', 'mechanism'], emoji: '⚙️' },
  { id: 'pulley', name: 'Pulley', category: 'common', tags: ['pulley', 'lift', 'rope', 'wheel', 'machine', 'hoist', 'mechanical'], emoji: '🔗' },
  { id: 'lever', name: 'Lever', category: 'common', tags: ['lever', 'pull', 'switch', 'mechanism', 'pivot', 'lift', 'force'], emoji: '🕹️' },
  { id: 'spring', name: 'Spring', category: 'common', tags: ['spring', 'coil', 'metal', 'bounce', 'elastic', 'tension', 'spiral'], emoji: '🌀' },
  { id: 'bolt', name: 'Bolt', category: 'common', tags: ['bolt', 'screw', 'metal', 'fasten', 'thread', 'nut', 'tighten'], emoji: '🔩' },
  { id: 'nail', name: 'Nail', category: 'common', tags: ['nail', 'hammer', 'metal', 'point', 'wood', 'fasten', 'sharp'], emoji: '📌' },
  { id: 'screwdriver', name: 'Screwdriver', category: 'common', tags: ['screwdriver', 'tool', 'turn', 'screw', 'fix', 'metal', 'handle'], emoji: '🪛' },
  { id: 'door', name: 'Door', category: 'common', tags: ['door', 'entrance', 'exit', 'wooden', 'open', 'close', 'handle'], emoji: '🚪' },
  { id: 'window', name: 'Window', category: 'common', tags: ['window', 'glass', 'view', 'frame', 'pane', 'light', 'open'], emoji: '🪟' },
  { id: 'sign_post', name: 'Sign Post', category: 'common', tags: ['sign', 'post', 'direction', 'wooden', 'road', 'arrow', 'guide'], emoji: '🪧' },
  { id: 'stool', name: 'Stool', category: 'common', tags: ['stool', 'seat', 'sit', 'short', 'wooden', 'bar', 'leg'], emoji: '🪑' },
  { id: 'rug', name: 'Rug', category: 'common', tags: ['rug', 'carpet', 'floor', 'fabric', 'pattern', 'weave', 'warm'], emoji: '🧶' },
];
