// Fantasy category sprites — magic items, mythical creatures, enchanted gear, potions
export const FANTASY_SPRITES = [
  { id: 'crystal_ball', name: 'Crystal Ball', category: 'fantasy', tags: ['crystal', 'ball', 'orb', 'magic', 'fortune', 'see', 'divine', 'sphere', 'glow', 'mystic'], emoji: '🔮' },
  { id: 'potion', name: 'Potion', category: 'fantasy', tags: ['potion', 'magic', 'bottle', 'elixir', 'brew', 'drink', 'alchemy', 'heal', 'liquid', 'bubbling'], emoji: '🧪' },
  { id: 'wand', name: 'Wand', category: 'fantasy', tags: ['wand', 'magic', 'spell', 'cast', 'wizard', 'fairy', 'star', 'wave'], emoji: '🪄' },
  { id: 'staff', name: 'Staff', category: 'fantasy', tags: ['staff', 'magic', 'wizard', 'tall', 'wooden', 'power', 'crystal', 'walk'], emoji: '🏑' },
  { id: 'scepter', name: 'Scepter', category: 'fantasy', tags: ['scepter', 'royal', 'power', 'gem', 'rule', 'authority', 'golden'], emoji: '👑' },
  { id: 'amulet', name: 'Amulet', category: 'fantasy', tags: ['amulet', 'necklace', 'protect', 'charm', 'magic', 'pendant', 'ward'], emoji: '🧿' },
  { id: 'talisman', name: 'Talisman', category: 'fantasy', tags: ['talisman', 'luck', 'protect', 'symbol', 'charm', 'power', 'ancient'], emoji: '🔱' },
  { id: 'charm', name: 'Charm', category: 'fantasy', tags: ['charm', 'luck', 'small', 'magic', 'trinket', 'enchant', 'bracelet'], emoji: '✨' },
  { id: 'rune_stone', name: 'Rune Stone', category: 'fantasy', tags: ['rune', 'stone', 'symbol', 'ancient', 'carve', 'norse', 'power'], emoji: '🪨' },
  { id: 'enchanted_ring', name: 'Enchanted Ring', category: 'fantasy', tags: ['ring', 'enchant', 'magic', 'band', 'glow', 'finger', 'power'], emoji: '💍' },
  { id: 'magic_mirror', name: 'Magic Mirror', category: 'fantasy', tags: ['mirror', 'magic', 'see', 'truth', 'reflect', 'enchant', 'oracle'], emoji: '🪞' },
  { id: 'flying_carpet', name: 'Flying Carpet', category: 'fantasy', tags: ['carpet', 'fly', 'magic', 'ride', 'weave', 'arabian', 'float'], emoji: '🧞' },
  { id: 'magic_lamp', name: 'Magic Lamp', category: 'fantasy', tags: ['lamp', 'genie', 'wish', 'rub', 'golden', 'smoke', 'arabian'], emoji: '🪔' },
  { id: 'phoenix_feather', name: 'Phoenix Feather', category: 'fantasy', tags: ['phoenix', 'feather', 'fire', 'glow', 'rare', 'rebirth', 'orange'], emoji: '🪶' },
  { id: 'dragon_scale', name: 'Dragon Scale', category: 'fantasy', tags: ['dragon', 'scale', 'armor', 'iridescent', 'tough', 'rare', 'shimmer'], emoji: '🐉' },
  { id: 'unicorn_horn', name: 'Unicorn Horn', category: 'fantasy', tags: ['unicorn', 'horn', 'spiral', 'white', 'pure', 'heal', 'magic'], emoji: '🦄' },
  { id: 'fairy_dust', name: 'Fairy Dust', category: 'fantasy', tags: ['fairy', 'dust', 'sparkle', 'fly', 'tiny', 'magic', 'golden'], emoji: '✨' },
  { id: 'wizard_hat', name: 'Wizard Hat', category: 'fantasy', tags: ['wizard', 'hat', 'star', 'cone', 'blue', 'magic', 'pointy'], emoji: '🧙' },
  { id: 'witch_hat', name: 'Witch Hat', category: 'fantasy', tags: ['witch', 'hat', 'black', 'pointy', 'brim', 'magic', 'halloween'], emoji: '🎃' },
  { id: 'cloak_invisibility', name: 'Cloak of Invisibility', category: 'fantasy', tags: ['cloak', 'invisible', 'hide', 'fabric', 'shimmer', 'vanish', 'stealth'], emoji: '🧥' },
  { id: 'enchanted_sword', name: 'Enchanted Sword', category: 'fantasy', tags: ['sword', 'enchant', 'glow', 'blade', 'hero', 'magic', 'steel'], emoji: '⚔️' },
  { id: 'runic_shield', name: 'Runic Shield', category: 'fantasy', tags: ['shield', 'rune', 'protect', 'glow', 'magic', 'ward', 'ancient'], emoji: '🛡️' },
  { id: 'mystic_bow', name: 'Mystic Bow', category: 'fantasy', tags: ['bow', 'arrow', 'magic', 'aim', 'glow', 'elven', 'shoot'], emoji: '🏹' },
  { id: 'portal_stone', name: 'Portal Stone', category: 'fantasy', tags: ['portal', 'stone', 'teleport', 'travel', 'glow', 'dimension', 'gate'], emoji: '🌀' },
  { id: 'teleport_gem', name: 'Teleport Gem', category: 'fantasy', tags: ['teleport', 'gem', 'flash', 'instant', 'travel', 'blink', 'purple'], emoji: '💠' },
  { id: 'time_turner', name: 'Time Turner', category: 'fantasy', tags: ['time', 'turn', 'hourglass', 'reverse', 'golden', 'spin', 'past'], emoji: '⏳' },
  { id: 'dream_catcher', name: 'Dream Catcher', category: 'fantasy', tags: ['dream', 'catch', 'web', 'feather', 'night', 'sleep', 'native'], emoji: '🕸️' },
  { id: 'wish_star', name: 'Wish Star', category: 'fantasy', tags: ['wish', 'star', 'glow', 'golden', 'hope', 'sky', 'shooting'], emoji: '⭐' },
  { id: 'lucky_coin', name: 'Lucky Coin', category: 'fantasy', tags: ['lucky', 'coin', 'gold', 'fortune', 'flip', 'clover', 'chance'], emoji: '🪙' },
  { id: 'chaos_orb', name: 'Chaos Orb', category: 'fantasy', tags: ['chaos', 'orb', 'swirl', 'dark', 'energy', 'unstable', 'power'], emoji: '🌑' },
  { id: 'mana_potion', name: 'Mana Potion', category: 'fantasy', tags: ['mana', 'potion', 'blue', 'magic', 'energy', 'restore', 'bottle'], emoji: '🧪' },
  { id: 'health_potion', name: 'Health Potion', category: 'fantasy', tags: ['health', 'potion', 'red', 'heal', 'restore', 'heart', 'bottle'], emoji: '❤️‍🩹' },
  { id: 'poison_vial', name: 'Poison Vial', category: 'fantasy', tags: ['poison', 'vial', 'green', 'toxic', 'danger', 'skull', 'liquid'], emoji: '☠️' },
  { id: 'fire_scroll', name: 'Fire Scroll', category: 'fantasy', tags: ['fire', 'scroll', 'spell', 'flame', 'burn', 'cast', 'ancient'], emoji: '📜' },
  { id: 'ice_crystal', name: 'Ice Crystal', category: 'fantasy', tags: ['ice', 'crystal', 'cold', 'frost', 'blue', 'sharp', 'freeze'], emoji: '❄️' },
  { id: 'thunder_stone', name: 'Thunder Stone', category: 'fantasy', tags: ['thunder', 'stone', 'lightning', 'crack', 'yellow', 'storm', 'power'], emoji: '⚡' },
  { id: 'shadow_essence', name: 'Shadow Essence', category: 'fantasy', tags: ['shadow', 'essence', 'dark', 'wisp', 'black', 'ghost', 'ethereal'], emoji: '🌑' },
  { id: 'light_prism', name: 'Light Prism', category: 'fantasy', tags: ['light', 'prism', 'rainbow', 'refract', 'crystal', 'spectrum', 'beam'], emoji: '🌈' },
  { id: 'void_pearl', name: 'Void Pearl', category: 'fantasy', tags: ['void', 'pearl', 'black', 'empty', 'abyss', 'sphere', 'dark'], emoji: '⚫' },
  { id: 'soul_gem', name: 'Soul Gem', category: 'fantasy', tags: ['soul', 'gem', 'glow', 'spirit', 'trap', 'ethereal', 'purple'], emoji: '💜' },
  { id: 'life_seed', name: 'Life Seed', category: 'fantasy', tags: ['life', 'seed', 'grow', 'green', 'glow', 'nature', 'sprout'], emoji: '🌱' },
  { id: 'death_mask', name: 'Death Mask', category: 'fantasy', tags: ['death', 'mask', 'face', 'golden', 'funeral', 'dark', 'ancient'], emoji: '🎭' },
  { id: 'dragon_egg_item', name: 'Dragon Egg', category: 'fantasy', tags: ['dragon', 'egg', 'scale', 'hatch', 'warm', 'rare', 'precious'], emoji: '🥚' },
  { id: 'phoenix_ash', name: 'Phoenix Ash', category: 'fantasy', tags: ['phoenix', 'ash', 'rebirth', 'fire', 'grey', 'warm', 'glow'], emoji: '🔥' },
  { id: 'mermaid_scale', name: 'Mermaid Scale', category: 'fantasy', tags: ['mermaid', 'scale', 'ocean', 'shimmer', 'blue', 'aqua', 'iridescent'], emoji: '🧜' },
  { id: 'griffin_feather', name: 'Griffin Feather', category: 'fantasy', tags: ['griffin', 'feather', 'gold', 'eagle', 'lion', 'majestic', 'rare'], emoji: '🦅' },
  { id: 'pegasus_wing', name: 'Pegasus Wing', category: 'fantasy', tags: ['pegasus', 'wing', 'white', 'fly', 'horse', 'feather', 'divine'], emoji: '🐴' },
  { id: 'minotaur_horn', name: 'Minotaur Horn', category: 'fantasy', tags: ['minotaur', 'horn', 'bull', 'maze', 'labyrinth', 'dark', 'strong'], emoji: '🐂' },
  { id: 'hydra_tooth', name: 'Hydra Tooth', category: 'fantasy', tags: ['hydra', 'tooth', 'fang', 'serpent', 'many', 'heads', 'venomous'], emoji: '🐍' },
  { id: 'basilisk_fang', name: 'Basilisk Fang', category: 'fantasy', tags: ['basilisk', 'fang', 'venom', 'serpent', 'petrify', 'deadly', 'curved'], emoji: '🐍' },
  { id: 'kraken_ink', name: 'Kraken Ink', category: 'fantasy', tags: ['kraken', 'ink', 'dark', 'ocean', 'tentacle', 'deep', 'bottle'], emoji: '🦑' },
  { id: 'vampire_fang', name: 'Vampire Fang', category: 'fantasy', tags: ['vampire', 'fang', 'blood', 'sharp', 'bite', 'night', 'pale'], emoji: '🧛' },
  { id: 'werewolf_claw', name: 'Werewolf Claw', category: 'fantasy', tags: ['werewolf', 'claw', 'moon', 'sharp', 'wild', 'transform', 'night'], emoji: '🐺' },
  { id: 'banshee_tear', name: 'Banshee Tear', category: 'fantasy', tags: ['banshee', 'tear', 'wail', 'ghost', 'sorrow', 'spirit', 'silver'], emoji: '👻' },
  { id: 'demon_eye', name: 'Demon Eye', category: 'fantasy', tags: ['demon', 'eye', 'red', 'evil', 'see', 'dark', 'slit'], emoji: '👁️' },
  { id: 'angel_wing', name: 'Angel Wing', category: 'fantasy', tags: ['angel', 'wing', 'white', 'feather', 'divine', 'holy', 'pure'], emoji: '😇' },
  { id: 'holy_water', name: 'Holy Water', category: 'fantasy', tags: ['holy', 'water', 'blessed', 'pure', 'vial', 'sacred', 'protect'], emoji: '💧' },
  { id: 'cursed_doll', name: 'Cursed Doll', category: 'fantasy', tags: ['cursed', 'doll', 'voodoo', 'pin', 'dark', 'puppet', 'hex'], emoji: '🧸' },
  { id: 'summoning_circle', name: 'Summoning Circle', category: 'fantasy', tags: ['summon', 'circle', 'rune', 'glow', 'ritual', 'magic', 'pentagram'], emoji: '⭕' },
  { id: 'prophecy_scroll', name: 'Prophecy Scroll', category: 'fantasy', tags: ['prophecy', 'scroll', 'future', 'fate', 'ancient', 'text', 'vision'], emoji: '📜' },
  { id: 'fate_dice', name: 'Fate Dice', category: 'fantasy', tags: ['fate', 'dice', 'roll', 'chance', 'destiny', 'rune', 'cast'], emoji: '🎲' },
  { id: 'destiny_thread', name: 'Destiny Thread', category: 'fantasy', tags: ['destiny', 'thread', 'weave', 'golden', 'fate', 'spin', 'connect'], emoji: '🧵' },
  { id: 'golem_core', name: 'Golem Core', category: 'fantasy', tags: ['golem', 'core', 'stone', 'animate', 'glow', 'rune', 'construct'], emoji: '🪨' },
  { id: 'witch_brew', name: 'Witch Brew', category: 'fantasy', tags: ['witch', 'brew', 'cauldron', 'bubble', 'green', 'potion', 'stir'], emoji: '🧙‍♀️' },
  { id: 'elf_bow', name: 'Elf Bow', category: 'fantasy', tags: ['elf', 'bow', 'elegant', 'arrow', 'forest', 'aim', 'carved'], emoji: '🏹' },
  { id: 'dwarf_helm', name: 'Dwarf Helm', category: 'fantasy', tags: ['dwarf', 'helm', 'metal', 'horned', 'mine', 'forge', 'sturdy'], emoji: '⛑️' },
  { id: 'enchanted_cloak', name: 'Enchanted Cloak', category: 'fantasy', tags: ['cloak', 'enchant', 'shimmer', 'wrap', 'protect', 'magic', 'flowing'], emoji: '🧥' },
  { id: 'spell_scroll', name: 'Spell Scroll', category: 'fantasy', tags: ['spell', 'scroll', 'magic', 'cast', 'parchment', 'rune', 'ancient'], emoji: '📜' },
  { id: 'arcane_tome', name: 'Arcane Tome', category: 'fantasy', tags: ['arcane', 'tome', 'book', 'magic', 'ancient', 'knowledge', 'rune'], emoji: '📕' },
  { id: 'mystic_orb', name: 'Mystic Orb', category: 'fantasy', tags: ['mystic', 'orb', 'glow', 'sphere', 'float', 'magic', 'energy'], emoji: '🔮' },
  { id: 'spirit_lantern', name: 'Spirit Lantern', category: 'fantasy', tags: ['spirit', 'lantern', 'ghost', 'glow', 'blue', 'soul', 'light'], emoji: '🏮' },
  { id: 'ghost_chain', name: 'Ghost Chain', category: 'fantasy', tags: ['ghost', 'chain', 'spirit', 'haunt', 'rattle', 'spectral', 'silver'], emoji: '👻' },
  { id: 'dark_crystal', name: 'Dark Crystal', category: 'fantasy', tags: ['dark', 'crystal', 'black', 'power', 'corrupt', 'shard', 'shadow'], emoji: '🖤' },
  { id: 'blood_ruby', name: 'Blood Ruby', category: 'fantasy', tags: ['blood', 'ruby', 'red', 'deep', 'vampire', 'dark', 'glow'], emoji: '❤️' },
  { id: 'frost_shard', name: 'Frost Shard', category: 'fantasy', tags: ['frost', 'shard', 'ice', 'cold', 'blue', 'sharp', 'crystal'], emoji: '🧊' },
  { id: 'storm_pearl', name: 'Storm Pearl', category: 'fantasy', tags: ['storm', 'pearl', 'lightning', 'grey', 'cloud', 'electric', 'sphere'], emoji: '🌩️' },
  { id: 'earth_stone', name: 'Earth Stone', category: 'fantasy', tags: ['earth', 'stone', 'brown', 'solid', 'nature', 'ground', 'primal'], emoji: '🪨' },
  { id: 'wind_chime_magic', name: 'Mystic Wind Chime', category: 'fantasy', tags: ['wind', 'chime', 'air', 'ring', 'breeze', 'melodic', 'silver'], emoji: '🎐' },
  { id: 'water_drop_magic', name: 'Living Water Drop', category: 'fantasy', tags: ['water', 'drop', 'living', 'blue', 'pure', 'spirit', 'flow'], emoji: '💧' },
  { id: 'fire_opal', name: 'Fire Opal', category: 'fantasy', tags: ['fire', 'opal', 'orange', 'flame', 'gem', 'glow', 'warm'], emoji: '🔥' },
  { id: 'nature_emerald', name: 'Nature Emerald', category: 'fantasy', tags: ['nature', 'emerald', 'green', 'life', 'grow', 'primal', 'verdant'], emoji: '💚' },
  { id: 'necromancer_staff', name: 'Necromancer Staff', category: 'fantasy', tags: ['necromancer', 'staff', 'skull', 'death', 'dark', 'undead', 'bone'], emoji: '☠️' },
  { id: 'paladin_shield', name: 'Paladin Shield', category: 'fantasy', tags: ['paladin', 'shield', 'holy', 'gold', 'protect', 'divine', 'crest'], emoji: '🛡️' },
  { id: 'warlock_eye', name: 'Warlock Eye', category: 'fantasy', tags: ['warlock', 'eye', 'see', 'purple', 'knowledge', 'dark', 'power'], emoji: '👁️' },
  { id: 'crystal_wand', name: 'Crystal Wand', category: 'fantasy', tags: ['crystal', 'wand', 'tip', 'channel', 'focus', 'clear', 'magic'], emoji: '🪄' },
];
