// Imaginary category sprites — surreal, nonsensical, Codex Seraphinianus-inspired made-up objects
export const IMAGINARY_SPRITES = [
  // Original 10
  { id: 'blorpascope', name: 'Blorpascope', category: 'imaginary', tags: ['jelly', 'telescope', 'eyeball', 'wobble', 'surreal', 'goofy', 'lens', 'squishy'], emoji: '👁️' },
  { id: 'snorkelwhisk', name: 'Snorkelwhisk', category: 'imaginary', tags: ['whisk', 'snorkel', 'bubble', 'kitchen', 'swim', 'surreal', 'metal', 'drip'], emoji: '🫧' },
  { id: 'flumberry', name: 'Flumberry', category: 'imaginary', tags: ['raspberry', 'marble', 'legs', 'fruit', 'walking', 'surreal', 'tiny', 'uphill'], emoji: '🫐' },
  { id: 'glintwurm', name: 'Glintwurm', category: 'imaginary', tags: ['worm', 'spectacle', 'lens', 'copper', 'wire', 'glint', 'surreal', 'segmented'], emoji: '🪱' },
  { id: 'quibblejack', name: 'Quibblejack', category: 'imaginary', tags: ['jack-in-the-box', 'two-headed', 'argue', 'spring', 'surreal', 'goofy', 'toy', 'chaos'], emoji: '🤹' },
  { id: 'frothspangle', name: 'Frothspangle', category: 'imaginary', tags: ['foam', 'cube', 'sparkle', 'purple', 'glow', 'hum', 'surreal', 'fizzy'], emoji: '🟪' },
  { id: 'wumblechog', name: 'Wumblechog', category: 'imaginary', tags: ['cogwheel', 'furry', 'sleepy', 'wooden', 'eyes', 'surreal', 'gear', 'creature'], emoji: '⚙️' },
  { id: 'skrinklepot', name: 'Skrinklepot', category: 'imaginary', tags: ['pot', 'recursive', 'infinite', 'nested', 'surreal', 'ceramic', 'fractal', 'paradox'], emoji: '🏺' },
  { id: 'nubblefork', name: 'Nubblefork', category: 'imaginary', tags: ['fork', 'round', 'knobby', 'cloud', 'tangle', 'surreal', 'utensil', 'soft'], emoji: '🍴' },
  { id: 'plindoscrew', name: 'Plindoscrew', category: 'imaginary', tags: ['screw', 'spiral', 'two-direction', 'impossible', 'surreal', 'metal', 'geometry', 'paradox'], emoji: '🔩' },

  // Batch 2: 11-20
  { id: 'glimperoo', name: 'Glimperoo', category: 'imaginary', tags: ['mirror', 'invisible', 'reflection', 'glass', 'surreal', 'paradox', 'ghost', 'peek'], emoji: '🪞' },
  { id: 'twazzlebin', name: 'Twazzlebin', category: 'imaginary', tags: ['trash', 'dimension', 'portal', 'container', 'surreal', 'sort', 'void', 'metal'], emoji: '🗑️' },
  { id: 'sproingfiddle', name: 'Sproingfiddle', category: 'imaginary', tags: ['violin', 'spring', 'coil', 'music', 'backwards', 'surreal', 'bounce', 'metal'], emoji: '🎻' },
  { id: 'clunkmelon', name: 'Clunkmelon', category: 'imaginary', tags: ['melon', 'clockwork', 'gear', 'ticking', 'fruit', 'surreal', 'mechanical', 'brass'], emoji: '🍈' },
  { id: 'wobblethorn', name: 'Wobblethorn', category: 'imaginary', tags: ['thorn', 'bush', 'jelly', 'wobble', 'plant', 'surreal', 'spike', 'squishy'], emoji: '🌵' },
  { id: 'snazzlecap', name: 'Snazzlecap', category: 'imaginary', tags: ['mushroom', 'hat', 'tophat', 'fancy', 'surreal', 'fungus', 'dapper', 'tiny'], emoji: '🎩' },
  { id: 'bumbleglass', name: 'Bumbleglass', category: 'imaginary', tags: ['magnifying', 'glass', 'blur', 'lens', 'surreal', 'reverse', 'fuzzy', 'optics'], emoji: '🔍' },
  { id: 'grinklesaw', name: 'Grinklesaw', category: 'imaginary', tags: ['saw', 'teeth', 'laugh', 'giggle', 'tool', 'surreal', 'metal', 'goofy'], emoji: '🪚' },
  { id: 'flibberknob', name: 'Flibberknob', category: 'imaginary', tags: ['doorknob', 'portal', 'random', 'door', 'surreal', 'brass', 'twist', 'travel'], emoji: '🚪' },
  { id: 'spudwhistle', name: 'Spudwhistle', category: 'imaginary', tags: ['potato', 'piccolo', 'music', 'vegetable', 'surreal', 'toot', 'root', 'wind'], emoji: '🥔' },

  // Batch 3: 21-30
  { id: 'quorklamp', name: 'Quorklamp', category: 'imaginary', tags: ['lamp', 'darkness', 'shadow', 'inverse', 'surreal', 'glow', 'void', 'light'], emoji: '🪔' },
  { id: 'fizzletongs', name: 'Fizzletongs', category: 'imaginary', tags: ['tongs', 'lightning', 'frozen', 'electric', 'surreal', 'ice', 'bolt', 'grip'], emoji: '⚡' },
  { id: 'drozzlepipe', name: 'Drozzlepipe', category: 'imaginary', tags: ['pipe', 'smoke', 'square', 'ring', 'surreal', 'puff', 'geometry', 'wood'], emoji: '🪈' },
  { id: 'winklebrace', name: 'Winklebrace', category: 'imaginary', tags: ['bracelet', 'eyeball', 'blink', 'chain', 'surreal', 'jewelry', 'watch', 'creepy'], emoji: '📿' },
  { id: 'splotchvane', name: 'Splotchvane', category: 'imaginary', tags: ['weather-vane', 'emotion', 'mood', 'arrow', 'surreal', 'feeling', 'wind', 'metal'], emoji: '🏴' },
  { id: 'crumblechime', name: 'Crumblechime', category: 'imaginary', tags: ['wind-chime', 'toast', 'crumb', 'bread', 'surreal', 'sound', 'breakfast', 'tinkle'], emoji: '🔔' },
  { id: 'gloopspoon', name: 'Gloopspoon', category: 'imaginary', tags: ['spoon', 'drip', 'upward', 'gravity', 'surreal', 'liquid', 'reverse', 'silver'], emoji: '🥄' },
  { id: 'tizzlewheel', name: 'Tizzlewheel', category: 'imaginary', tags: ['wheel', 'triangle', 'spoke', 'roll', 'surreal', 'geometry', 'impossible', 'wood'], emoji: '☸️' },
  { id: 'munkledrum', name: 'Munkledrum', category: 'imaginary', tags: ['drum', 'silence', 'quiet', 'sound', 'surreal', 'mute', 'percussion', 'void'], emoji: '🥁' },
  { id: 'skwibpencil', name: 'Skwibpencil', category: 'imaginary', tags: ['pencil', 'smell', 'scent', 'write', 'surreal', 'aroma', 'draw', 'synesthesia'], emoji: '✏️' },

  // Batch 4: 31-40
  { id: 'bozzlecrown', name: 'Bozzlecrown', category: 'imaginary', tags: ['crown', 'question-mark', 'tangle', 'gold', 'surreal', 'royal', 'puzzle', 'metal'], emoji: '👑' },
  { id: 'flumpsaddle', name: 'Flumpsaddle', category: 'imaginary', tags: ['saddle', 'cloud', 'deflate', 'ride', 'surreal', 'soft', 'puff', 'leather'], emoji: '🪑' },
  { id: 'grizzlethimble', name: 'Grizzlethimble', category: 'imaginary', tags: ['thimble', 'fur', 'bear', 'sewing', 'surreal', 'tiny', 'fuzzy', 'metal'], emoji: '🧵' },
  { id: 'plonkanchor', name: 'Plonkanchor', category: 'imaginary', tags: ['anchor', 'rubber', 'bounce', 'boat', 'surreal', 'flexible', 'float', 'naval'], emoji: '⚓' },
  { id: 'twerpbottle', name: 'Twerpbottle', category: 'imaginary', tags: ['bottle', 'bigger-inside', 'tardis', 'glass', 'surreal', 'space', 'paradox', 'container'], emoji: '🍾' },
  { id: 'snugglerack', name: 'Snugglerack', category: 'imaginary', tags: ['coat-rack', 'hug', 'arms', 'wood', 'surreal', 'warm', 'embrace', 'furniture'], emoji: '🧸' },
  { id: 'wibblestamp', name: 'Wibblestamp', category: 'imaginary', tags: ['stamp', 'random', 'print', 'change', 'surreal', 'ink', 'rubber', 'surprise'], emoji: '📮' },
  { id: 'crogglebell', name: 'Crogglebell', category: 'imaginary', tags: ['bell', 'precognition', 'early', 'ring', 'surreal', 'brass', 'time', 'prophetic'], emoji: '🔔' },
  { id: 'dimplechurn', name: 'Dimplechurn', category: 'imaginary', tags: ['churn', 'butter', 'stars', 'sparkle', 'surreal', 'galaxy', 'wooden', 'cosmic'], emoji: '🌟' },
  { id: 'fizzanvil', name: 'Fizzanvil', category: 'imaginary', tags: ['anvil', 'bubble', 'soap', 'float', 'surreal', 'fragile', 'iridescent', 'forge'], emoji: '🫧' },

  // Batch 5: 41-50
  { id: 'glorpfunnel', name: 'Glorpfunnel', category: 'imaginary', tags: ['funnel', 'reverse', 'flow', 'liquid', 'surreal', 'upward', 'pour', 'metal'], emoji: '🔄' },
  { id: 'humblevise', name: 'Humblevise', category: 'imaginary', tags: ['vise', 'marshmallow', 'soft', 'grip', 'surreal', 'gentle', 'squishy', 'tool'], emoji: '🍡' },
  { id: 'jitterscale', name: 'Jitterscale', category: 'imaginary', tags: ['scale', 'dance', 'balance', 'weigh', 'surreal', 'jitter', 'brass', 'move'], emoji: '⚖️' },
  { id: 'knottpliers', name: 'Knottpliers', category: 'imaginary', tags: ['pliers', 'bow', 'knot', 'tie', 'surreal', 'metal', 'pretty', 'tool'], emoji: '🎀' },
  { id: 'lumpcandle', name: 'Lumpcandle', category: 'imaginary', tags: ['candle', 'ice', 'upward', 'drip', 'surreal', 'cold', 'flame', 'reverse'], emoji: '🕯️' },
  { id: 'mizzleclock', name: 'Mizzleclock', category: 'imaginary', tags: ['clock', 'maybe', 'uncertain', 'time', 'surreal', 'vague', 'hands', 'brass'], emoji: '🕰️' },
  { id: 'noodlehook', name: 'Noodlehook', category: 'imaginary', tags: ['hook', 'spaghetti', 'pasta', 'fish', 'surreal', 'noodle', 'strong', 'food'], emoji: '🪝' },
  { id: 'pluffcompass', name: 'Pluffcompass', category: 'imaginary', tags: ['compass', 'nap', 'sleep', 'pillow', 'surreal', 'direction', 'cozy', 'brass'], emoji: '🧭' },
  { id: 'quazzlebroom', name: 'Quazzlebroom', category: 'imaginary', tags: ['broom', 'dirt', 'create', 'mess', 'surreal', 'sweep', 'reverse', 'wood'], emoji: '🧹' },
  { id: 'rumblethreads', name: 'Rumblethreads', category: 'imaginary', tags: ['thread', 'vibrate', 'hum', 'lullaby', 'surreal', 'music', 'fiber', 'spool'], emoji: '🧶' },

  // Batch 6: 51-60
  { id: 'sizzlecork', name: 'Sizzlecork', category: 'imaginary', tags: ['cork', 'fire', 'burn', 'immune', 'surreal', 'flame', 'wine', 'eternal'], emoji: '🔥' },
  { id: 'tumblecrayon', name: 'Tumblecrayon', category: 'imaginary', tags: ['crayon', 'color', 'outside', 'rebel', 'surreal', 'draw', 'wax', 'art'], emoji: '🖍️' },
  { id: 'vexdial', name: 'Vexdial', category: 'imaginary', tags: ['dial', 'rotary', 'call', 'object', 'surreal', 'phone', 'summon', 'brass'], emoji: '📞' },
  { id: 'wugglebox', name: 'Wugglebox', category: 'imaginary', tags: ['box', 'shape-shift', 'misfit', 'container', 'surreal', 'morph', 'wooden', 'rebel'], emoji: '📦' },
  { id: 'yawnchisel', name: 'Yawnchisel', category: 'imaginary', tags: ['chisel', 'pillow', 'sculpt', 'stone', 'surreal', 'soft', 'sleepy', 'tool'], emoji: '🪨' },
  { id: 'zibberchain', name: 'Zibberchain', category: 'imaginary', tags: ['chain', 'galaxy', 'spin', 'cosmic', 'surreal', 'link', 'stars', 'metal'], emoji: '⛓️' },
  { id: 'blotterfly', name: 'Blotterfly', category: 'imaginary', tags: ['butterfly', 'ink', 'blot', 'write', 'surreal', 'wing', 'paper', 'insect'], emoji: '🦋' },
  { id: 'chortlewrench', name: 'Chortlewrench', category: 'imaginary', tags: ['wrench', 'laugh', 'chortle', 'turn', 'surreal', 'metal', 'goofy', 'tool'], emoji: '🔧' },
  { id: 'dribbleclamp', name: 'Dribbleclamp', category: 'imaginary', tags: ['clamp', 'tears', 'joy', 'hold', 'surreal', 'wet', 'emotional', 'metal'], emoji: '😂' },
  { id: 'fwipmagnet', name: 'Fwipmagnet', category: 'imaginary', tags: ['magnet', 'forgotten', 'memory', 'attract', 'surreal', 'pull', 'lost', 'metal'], emoji: '🧲' },

  // Batch 7: 61-70
  { id: 'guffawpeg', name: 'Guffawpeg', category: 'imaginary', tags: ['clothespin', 'sound', 'clip', 'catch', 'surreal', 'audio', 'wood', 'pinch'], emoji: '📌' },
  { id: 'hiccupnail', name: 'Hiccupnail', category: 'imaginary', tags: ['nail', 'jump', 'hammer', 'hop', 'surreal', 'metal', 'bounce', 'shy'], emoji: '📍' },
  { id: 'inklestrop', name: 'Inklestrop', category: 'imaginary', tags: ['strop', 'leather', 'color', 'sharpen', 'surreal', 'bright', 'polish', 'rainbow'], emoji: '🌈' },
  { id: 'jumblesieve', name: 'Jumblesieve', category: 'imaginary', tags: ['sieve', 'absurdity', 'sort', 'filter', 'surreal', 'mesh', 'rank', 'metal'], emoji: '🕳️' },
  { id: 'kerfuzzle', name: 'Kerfuzzle', category: 'imaginary', tags: ['lint', 'math', 'solve', 'ball', 'surreal', 'fuzzy', 'genius', 'compute'], emoji: '🧮' },
  { id: 'lurkpinion', name: 'Lurkpinion', category: 'imaginary', tags: ['gear', 'observe', 'shy', 'turn', 'surreal', 'metal', 'hide', 'watch'], emoji: '👀' },
  { id: 'mufflecaliper', name: 'Mufflecaliper', category: 'imaginary', tags: ['caliper', 'whisper', 'measure', 'quiet', 'surreal', 'brass', 'precise', 'soft'], emoji: '📏' },
  { id: 'nibblechisel', name: 'Nibblechisel', category: 'imaginary', tags: ['chisel', 'bite', 'carve', 'eat', 'surreal', 'teeth', 'stone', 'hungry'], emoji: '🦷' },
  { id: 'oozecasket', name: 'Oozecasket', category: 'imaginary', tags: ['chest', 'rainbow', 'leak', 'ooze', 'surreal', 'hinge', 'treasure', 'drip'], emoji: '🌈' },
  { id: 'puckerbolt', name: 'Puckerbolt', category: 'imaginary', tags: ['bolt', 'lips', 'pucker', 'tighten', 'surreal', 'metal', 'kiss', 'hardware'], emoji: '💋' },

  // Batch 8: 71-80
  { id: 'quiverladle', name: 'Quiverladle', category: 'imaginary', tags: ['ladle', 'tremble', 'soup', 'excited', 'surreal', 'silver', 'shake', 'kitchen'], emoji: '🥣' },
  { id: 'razzlesextant', name: 'Razzlesextant', category: 'imaginary', tags: ['sextant', 'mood', 'navigate', 'emotion', 'surreal', 'brass', 'star', 'feeling'], emoji: '🔭' },
  { id: 'smirkvalve', name: 'Smirkvalve', category: 'imaginary', tags: ['valve', 'grin', 'pressure', 'face', 'surreal', 'brass', 'smile', 'pipe'], emoji: '😏' },
  { id: 'tumblereed', name: 'Tumblereed', category: 'imaginary', tags: ['reed', 'tumble', 'uphill', 'hollow', 'surreal', 'roll', 'plant', 'wind'], emoji: '🌾' },
  { id: 'umbrawhisk', name: 'Umbrawhisk', category: 'imaginary', tags: ['whisk', 'shadow', 'light', 'beat', 'surreal', 'dark', 'cream', 'kitchen'], emoji: '🌑' },
  { id: 'vexbellows', name: 'Vexbellows', category: 'imaginary', tags: ['bellows', 'fire', 'snow', 'inhale', 'surreal', 'reverse', 'forge', 'cold'], emoji: '❄️' },
  { id: 'wibblescope', name: 'Wibblescope', category: 'imaginary', tags: ['periscope', 'yesterday', 'time', 'view', 'surreal', 'past', 'tube', 'brass'], emoji: '🔭' },
  { id: 'xerxesloom', name: 'Xerxesloom', category: 'imaginary', tags: ['loom', 'static', 'electricity', 'weave', 'surreal', 'fabric', 'spark', 'tiny'], emoji: '⚡' },
  { id: 'yelpgauge', name: 'Yelpgauge', category: 'imaginary', tags: ['gauge', 'yelp', 'pressure', 'sound', 'surreal', 'brass', 'measure', 'loud'], emoji: '📢' },
  { id: 'zestgrater', name: 'Zestgrater', category: 'imaginary', tags: ['grater', 'enthusiasm', 'add', 'zest', 'surreal', 'metal', 'energy', 'kitchen'], emoji: '🤩' },

  // Batch 9: 81-90
  { id: 'blunderbung', name: 'Blunderbung', category: 'imaginary', tags: ['cork', 'launch', 'bottle', 'bounce', 'surreal', 'projectile', 'pop', 'return'], emoji: '🍾' },
  { id: 'chuffleprism', name: 'Chuffleprism', category: 'imaginary', tags: ['prism', 'sound', 'color', 'split', 'surreal', 'glass', 'synesthesia', 'crystal'], emoji: '🔮' },
  { id: 'dwibblecleat', name: 'Dwibblecleat', category: 'imaginary', tags: ['cleat', 'bubblegum', 'boat', 'sticky', 'surreal', 'dried', 'pink', 'naval'], emoji: '🫧' },
  { id: 'fnurrlepiston', name: 'Fnurrlepiston', category: 'imaginary', tags: ['piston', 'circle', 'spin', 'engine', 'surreal', 'metal', 'round', 'impossible'], emoji: '🔄' },
  { id: 'gribbleawl', name: 'Gribbleawl', category: 'imaginary', tags: ['awl', 'concept', 'poke', 'idea', 'surreal', 'abstract', 'sharp', 'thought'], emoji: '💭' },
  { id: 'hubblerivet', name: 'Hubblerivet', category: 'imaginary', tags: ['rivet', 'respect', 'bond', 'hold', 'surreal', 'metal', 'polite', 'connection'], emoji: '🤝' },
  { id: 'ickletrowel', name: 'Ickletrowel', category: 'imaginary', tags: ['trowel', 'confusion', 'plant', 'seed', 'surreal', 'garden', 'chaos', 'dirt'], emoji: '🌱' },
  { id: 'joltpipette', name: 'Joltpipette', category: 'imaginary', tags: ['pipette', 'lightning', 'drop', 'tiny', 'surreal', 'glass', 'electric', 'lab'], emoji: '⚡' },
  { id: 'knobbleratchet', name: 'Knobbleratchet', category: 'imaginary', tags: ['ratchet', 'melody', 'click', 'music', 'surreal', 'metal', 'song', 'tool'], emoji: '🎵' },
  { id: 'lumoxledger', name: 'Lumoxledger', category: 'imaginary', tags: ['book', 'rearrange', 'blink', 'page', 'surreal', 'paper', 'shift', 'text'], emoji: '📖' },

  // Batch 10: 91-100
  { id: 'mudgetap', name: 'Mudgetap', category: 'imaginary', tags: ['faucet', 'fog', 'flavor', 'mist', 'surreal', 'brass', 'pour', 'weather'], emoji: '🚰' },
  { id: 'nifflerule', name: 'Nifflerule', category: 'imaginary', tags: ['ruler', 'nonsense', 'measure', 'unit', 'surreal', 'wood', 'absurd', 'length'], emoji: '📐' },
  { id: 'oinkmortar', name: 'Oinkmortar', category: 'imaginary', tags: ['mortar', 'pestle', 'silence', 'noise', 'surreal', 'grind', 'stone', 'pig'], emoji: '🐷' },
  { id: 'plinkcrucible', name: 'Plinkcrucible', category: 'imaginary', tags: ['crucible', 'idea', 'melt', 'liquid', 'surreal', 'thought', 'ceramic', 'hot'], emoji: '🧪' },
  { id: 'quazzlevice', name: 'Quazzlevice', category: 'imaginary', tags: ['vice', 'time', 'squeeze', 'revert', 'surreal', 'metal', 'paradox', 'tool'], emoji: '🔙' },
  { id: 'rumblewasher', name: 'Rumblewasher', category: 'imaginary', tags: ['washer', 'shanty', 'hum', 'sea', 'surreal', 'metal', 'music', 'hardware'], emoji: '🎶' },
  { id: 'snigglevalve', name: 'Snigglevalve', category: 'imaginary', tags: ['valve', 'serpent', 'ouroboros', 'coil', 'surreal', 'brass', 'snake', 'eternal'], emoji: '🐍' },
  { id: 'twerpcalipers', name: 'Twerpcalipers', category: 'imaginary', tags: ['caliper', 'sarcasm', 'measure', 'snark', 'surreal', 'brass', 'precise', 'attitude'], emoji: '😒' },
  { id: 'umbleshears', name: 'Umbleshears', category: 'imaginary', tags: ['scissors', 'silence', 'awkward', 'cut', 'surreal', 'metal', 'social', 'blade'], emoji: '✂️' },
  { id: 'vortexthimble', name: 'Vortexthimble', category: 'imaginary', tags: ['thimble', 'whirlpool', 'vortex', 'tiny', 'surreal', 'metal', 'swirl', 'sewing'], emoji: '🌀' },
];
