// Knowledge category sprites — science, instruments, writing, music, navigation, education
export const KNOWLEDGE_SPRITES = [
  { id: 'spellbook', name: 'Spellbook', category: 'knowledge', tags: ['spell', 'book', 'magic', 'wizard', 'grimoire', 'ancient', 'incantation', 'runes', 'arcane'], emoji: '📖' },
  { id: 'hourglass', name: 'Hourglass', category: 'knowledge', tags: ['hourglass', 'time', 'sand', 'timer', 'ancient', 'measure', 'passing', 'glass', 'patience'], emoji: '⏳' },
  { id: 'compass', name: 'Compass', category: 'knowledge', tags: ['compass', 'direction', 'north', 'navigate', 'travel', 'explore', 'map', 'guide', 'brass'], emoji: '🧭' },
  { id: 'scroll', name: 'Scroll', category: 'knowledge', tags: ['scroll', 'parchment', 'write', 'ancient', 'roll', 'message', 'text'], emoji: '📜' },
  { id: 'quill', name: 'Quill', category: 'knowledge', tags: ['quill', 'write', 'feather', 'ink', 'pen', 'script', 'calligraphy'], emoji: '🪶' },
  { id: 'ink_bottle', name: 'Ink Bottle', category: 'knowledge', tags: ['ink', 'bottle', 'write', 'black', 'quill', 'dip', 'stain'], emoji: '🖋️' },
  { id: 'parchment', name: 'Parchment', category: 'knowledge', tags: ['parchment', 'paper', 'write', 'old', 'yellowed', 'roll', 'ancient'], emoji: '📃' },
  { id: 'abacus', name: 'Abacus', category: 'knowledge', tags: ['abacus', 'count', 'bead', 'math', 'calculate', 'wooden', 'ancient'], emoji: '🧮' },
  { id: 'telescope', name: 'Telescope', category: 'knowledge', tags: ['telescope', 'star', 'sky', 'see', 'zoom', 'brass', 'astronomy'], emoji: '🔭' },
  { id: 'microscope', name: 'Microscope', category: 'knowledge', tags: ['microscope', 'tiny', 'zoom', 'science', 'lens', 'discover', 'lab'], emoji: '🔬' },
  { id: 'magnifying_glass', name: 'Magnifying Glass', category: 'knowledge', tags: ['magnify', 'glass', 'lens', 'search', 'inspect', 'enlarge', 'detective'], emoji: '🔍' },
  { id: 'globe', name: 'Globe', category: 'knowledge', tags: ['globe', 'world', 'earth', 'spin', 'map', 'geography', 'sphere'], emoji: '🌍' },
  { id: 'astrolabe', name: 'Astrolabe', category: 'knowledge', tags: ['astrolabe', 'star', 'navigation', 'brass', 'ancient', 'astronomy', 'disc'], emoji: '🌟' },
  { id: 'sundial', name: 'Sundial', category: 'knowledge', tags: ['sundial', 'sun', 'time', 'shadow', 'stone', 'gnomon', 'garden'], emoji: '☀️' },
  { id: 'sextant', name: 'Sextant', category: 'knowledge', tags: ['sextant', 'navigate', 'sea', 'star', 'angle', 'brass', 'sailor'], emoji: '📐' },
  { id: 'barometer', name: 'Barometer', category: 'knowledge', tags: ['barometer', 'pressure', 'weather', 'mercury', 'measure', 'brass', 'dial'], emoji: '🌡️' },
  { id: 'thermometer', name: 'Thermometer', category: 'knowledge', tags: ['thermometer', 'temperature', 'heat', 'cold', 'mercury', 'measure', 'glass'], emoji: '🌡️' },
  { id: 'test_tube', name: 'Test Tube', category: 'knowledge', tags: ['test', 'tube', 'science', 'lab', 'glass', 'liquid', 'experiment'], emoji: '🧪' },
  { id: 'flask', name: 'Flask', category: 'knowledge', tags: ['flask', 'science', 'lab', 'glass', 'round', 'liquid', 'chemistry'], emoji: '⚗️' },
  { id: 'beaker', name: 'Beaker', category: 'knowledge', tags: ['beaker', 'science', 'lab', 'glass', 'pour', 'measure', 'chemistry'], emoji: '🧪' },
  { id: 'prism', name: 'Prism', category: 'knowledge', tags: ['prism', 'light', 'rainbow', 'glass', 'refract', 'triangle', 'spectrum'], emoji: '🌈' },
  { id: 'lens', name: 'Lens', category: 'knowledge', tags: ['lens', 'glass', 'focus', 'see', 'optics', 'round', 'convex'], emoji: '🔍' },
  { id: 'pendulum', name: 'Pendulum', category: 'knowledge', tags: ['pendulum', 'swing', 'weight', 'tick', 'gravity', 'motion', 'clock'], emoji: '🕰️' },
  { id: 'metronome', name: 'Metronome', category: 'knowledge', tags: ['metronome', 'beat', 'tempo', 'tick', 'music', 'rhythm', 'swing'], emoji: '🎵' },
  { id: 'tuning_fork', name: 'Tuning Fork', category: 'knowledge', tags: ['tuning', 'fork', 'vibrate', 'pitch', 'sound', 'metal', 'tone'], emoji: '🎶' },
  { id: 'music_box', name: 'Music Box', category: 'knowledge', tags: ['music', 'box', 'melody', 'wind', 'chime', 'dancer', 'ornate'], emoji: '🎶' },
  { id: 'harp', name: 'Harp', category: 'knowledge', tags: ['harp', 'string', 'music', 'pluck', 'golden', 'angel', 'melody'], emoji: '🎵' },
  { id: 'lute', name: 'Lute', category: 'knowledge', tags: ['lute', 'string', 'music', 'bard', 'strum', 'medieval', 'wooden'], emoji: '🎸' },
  { id: 'flute', name: 'Flute', category: 'knowledge', tags: ['flute', 'wind', 'music', 'blow', 'silver', 'hole', 'melody'], emoji: '🪈' },
  { id: 'drum', name: 'Drum', category: 'knowledge', tags: ['drum', 'beat', 'music', 'hit', 'rhythm', 'skin', 'loud'], emoji: '🥁' },
  { id: 'horn_instrument', name: 'Horn', category: 'knowledge', tags: ['horn', 'blow', 'music', 'brass', 'loud', 'call', 'herald'], emoji: '📯' },
  { id: 'violin', name: 'Violin', category: 'knowledge', tags: ['violin', 'string', 'bow', 'music', 'classical', 'melody', 'wood'], emoji: '🎻' },
  { id: 'piano_keys', name: 'Piano Keys', category: 'knowledge', tags: ['piano', 'key', 'music', 'black', 'white', 'play', 'chord'], emoji: '🎹' },
  { id: 'trumpet', name: 'Trumpet', category: 'knowledge', tags: ['trumpet', 'brass', 'blow', 'music', 'fanfare', 'loud', 'valve'], emoji: '🎺' },
  { id: 'ocarina', name: 'Ocarina', category: 'knowledge', tags: ['ocarina', 'wind', 'music', 'clay', 'hole', 'ancient', 'breathy'], emoji: '🎵' },
  { id: 'lyre', name: 'Lyre', category: 'knowledge', tags: ['lyre', 'string', 'music', 'greek', 'pluck', 'ancient', 'apollo'], emoji: '🎵' },
  { id: 'gong', name: 'Gong', category: 'knowledge', tags: ['gong', 'ring', 'hit', 'brass', 'deep', 'temple', 'vibrate'], emoji: '🔔' },
  { id: 'tambourine', name: 'Tambourine', category: 'knowledge', tags: ['tambourine', 'shake', 'jingle', 'music', 'rhythm', 'dance', 'round'], emoji: '🪘' },
  { id: 'typewriter', name: 'Typewriter', category: 'knowledge', tags: ['typewriter', 'type', 'key', 'write', 'click', 'paper', 'vintage'], emoji: '⌨️' },
  { id: 'camera', name: 'Camera', category: 'knowledge', tags: ['camera', 'photo', 'lens', 'capture', 'flash', 'snap', 'image'], emoji: '📷' },
  { id: 'lightbulb', name: 'Lightbulb', category: 'knowledge', tags: ['lightbulb', 'idea', 'glow', 'bright', 'electric', 'filament', 'invent'], emoji: '💡' },
  { id: 'magnet', name: 'Magnet', category: 'knowledge', tags: ['magnet', 'attract', 'metal', 'pole', 'horseshoe', 'pull', 'force'], emoji: '🧲' },
  { id: 'map_rolled', name: 'Rolled Map', category: 'knowledge', tags: ['map', 'roll', 'navigate', 'land', 'route', 'treasure', 'parchment'], emoji: '🗺️' },
  { id: 'blueprint', name: 'Blueprint', category: 'knowledge', tags: ['blueprint', 'plan', 'build', 'blue', 'design', 'architect', 'draw'], emoji: '📐' },
  { id: 'protractor', name: 'Protractor', category: 'knowledge', tags: ['protractor', 'angle', 'measure', 'math', 'degree', 'half', 'circle'], emoji: '📐' },
  { id: 'ruler', name: 'Ruler', category: 'knowledge', tags: ['ruler', 'measure', 'straight', 'length', 'mark', 'edge', 'line'], emoji: '📏' },
  { id: 'chalk', name: 'Chalk', category: 'knowledge', tags: ['chalk', 'write', 'white', 'draw', 'board', 'dust', 'teach'], emoji: '🖍️' },
  { id: 'blackboard', name: 'Blackboard', category: 'knowledge', tags: ['blackboard', 'chalk', 'write', 'teach', 'school', 'erase', 'lesson'], emoji: '📋' },
  { id: 'diploma', name: 'Diploma', category: 'knowledge', tags: ['diploma', 'graduate', 'scroll', 'achieve', 'school', 'ribbon', 'seal'], emoji: '📜' },
  { id: 'medal', name: 'Medal', category: 'knowledge', tags: ['medal', 'award', 'honor', 'round', 'ribbon', 'gold', 'achievement'], emoji: '🏅' },
  { id: 'trophy', name: 'Trophy', category: 'knowledge', tags: ['trophy', 'win', 'cup', 'gold', 'first', 'champion', 'prize'], emoji: '🏆' },
  { id: 'bookmark', name: 'Bookmark', category: 'knowledge', tags: ['bookmark', 'page', 'read', 'ribbon', 'save', 'mark', 'book'], emoji: '🔖' },
  { id: 'encyclopedia', name: 'Encyclopedia', category: 'knowledge', tags: ['encyclopedia', 'book', 'knowledge', 'volume', 'thick', 'reference', 'learn'], emoji: '📚' },
  { id: 'atlas', name: 'Atlas', category: 'knowledge', tags: ['atlas', 'map', 'book', 'world', 'geography', 'country', 'travel'], emoji: '🗺️' },
  { id: 'calculator', name: 'Calculator', category: 'knowledge', tags: ['calculator', 'math', 'number', 'compute', 'button', 'screen', 'add'], emoji: '🔢' },
  { id: 'battery', name: 'Battery', category: 'knowledge', tags: ['battery', 'energy', 'power', 'charge', 'electric', 'cell', 'volt'], emoji: '🔋' },
  { id: 'compass_drawing', name: 'Drawing Compass', category: 'knowledge', tags: ['compass', 'draw', 'circle', 'point', 'arc', 'math', 'metal'], emoji: '📐' },
  { id: 'laboratory_flask', name: 'Laboratory Flask', category: 'knowledge', tags: ['laboratory', 'flask', 'erlenmeyer', 'science', 'glass', 'narrow', 'experiment'], emoji: '⚗️' },
  { id: 'bunsen_burner', name: 'Bunsen Burner', category: 'knowledge', tags: ['bunsen', 'burner', 'flame', 'heat', 'lab', 'gas', 'science'], emoji: '🔥' },
  { id: 'periodic_table', name: 'Periodic Table', category: 'knowledge', tags: ['periodic', 'table', 'element', 'chemistry', 'atom', 'chart', 'science'], emoji: '⚛️' },
  { id: 'star_chart', name: 'Star Chart', category: 'knowledge', tags: ['star', 'chart', 'constellation', 'night', 'astronomy', 'map', 'celestial'], emoji: '🌌' },
  { id: 'celestial_globe', name: 'Celestial Globe', category: 'knowledge', tags: ['celestial', 'globe', 'star', 'sphere', 'sky', 'astronomy', 'constellation'], emoji: '🌐' },
  { id: 'pocket_watch', name: 'Pocket Watch', category: 'knowledge', tags: ['pocket', 'watch', 'time', 'chain', 'gold', 'tick', 'vintage'], emoji: '⌚' },
  { id: 'monocle', name: 'Monocle', category: 'knowledge', tags: ['monocle', 'eye', 'glass', 'lens', 'see', 'round', 'gentleman'], emoji: '🧐' },
  { id: 'gramophone', name: 'Gramophone', category: 'knowledge', tags: ['gramophone', 'music', 'horn', 'record', 'vinyl', 'play', 'vintage'], emoji: '📻' },
  { id: 'telegraph', name: 'Telegraph', category: 'knowledge', tags: ['telegraph', 'morse', 'code', 'tap', 'message', 'wire', 'communicate'], emoji: '📡' },
  { id: 'printing_press', name: 'Printing Press', category: 'knowledge', tags: ['printing', 'press', 'letter', 'ink', 'page', 'gutenberg', 'type'], emoji: '🖨️' },
  { id: 'stethoscope', name: 'Stethoscope', category: 'knowledge', tags: ['stethoscope', 'listen', 'heart', 'doctor', 'medical', 'tube', 'ear'], emoji: '🩺' },
  { id: 'gyroscope', name: 'Gyroscope', category: 'knowledge', tags: ['gyroscope', 'spin', 'balance', 'ring', 'physics', 'axis', 'metal'], emoji: '🌀' },
  { id: 'sand_timer', name: 'Sand Timer', category: 'knowledge', tags: ['sand', 'timer', 'glass', 'minute', 'flow', 'count', 'turn'], emoji: '⏳' },
  { id: 'equation_board', name: 'Equation Board', category: 'knowledge', tags: ['equation', 'board', 'math', 'formula', 'solve', 'chalk', 'algebra'], emoji: '🔢' },
  { id: 'circuit_board', name: 'Circuit Board', category: 'knowledge', tags: ['circuit', 'board', 'electronic', 'chip', 'green', 'trace', 'tech'], emoji: '🔌' },
  { id: 'journal', name: 'Journal', category: 'knowledge', tags: ['journal', 'write', 'diary', 'leather', 'note', 'record', 'personal'], emoji: '📓' },
  { id: 'quill_pen', name: 'Quill Pen', category: 'knowledge', tags: ['quill', 'pen', 'write', 'feather', 'nib', 'ink', 'elegant'], emoji: '✒️' },
  { id: 'ink_well', name: 'Ink Well', category: 'knowledge', tags: ['ink', 'well', 'pot', 'dip', 'black', 'glass', 'write'], emoji: '🖋️' },
  { id: 'papyrus', name: 'Papyrus', category: 'knowledge', tags: ['papyrus', 'ancient', 'egypt', 'write', 'reed', 'scroll', 'text'], emoji: '📜' },
  { id: 'set_square', name: 'Set Square', category: 'knowledge', tags: ['set', 'square', 'triangle', 'angle', 'draw', 'measure', 'ruler'], emoji: '📐' },
];
