// Misc category sprites — food, weapons, games, accessories, symbols, toys
export const MISC_SPRITES = [
  { id: 'skull', name: 'Skull', category: 'misc', tags: ['skull', 'death', 'bone', 'skeleton', 'pirate', 'danger', 'halloween', 'spooky', 'relic'], emoji: '💀' },
  { id: 'apple', name: 'Apple', category: 'misc', tags: ['apple', 'fruit', 'red', 'eat', 'health', 'teacher', 'crisp'], emoji: '🍎' },
  { id: 'bread', name: 'Bread', category: 'misc', tags: ['bread', 'loaf', 'bake', 'wheat', 'crust', 'food', 'slice'], emoji: '🍞' },
  { id: 'cheese', name: 'Cheese', category: 'misc', tags: ['cheese', 'yellow', 'hole', 'dairy', 'wedge', 'aged', 'food'], emoji: '🧀' },
  { id: 'wine_bottle', name: 'Wine Bottle', category: 'misc', tags: ['wine', 'bottle', 'red', 'drink', 'grape', 'cork', 'glass'], emoji: '🍷' },
  { id: 'beer_mug', name: 'Beer Mug', category: 'misc', tags: ['beer', 'mug', 'foam', 'drink', 'ale', 'tavern', 'handle'], emoji: '🍺' },
  { id: 'pie', name: 'Pie', category: 'misc', tags: ['pie', 'bake', 'crust', 'fruit', 'slice', 'golden', 'warm'], emoji: '🥧' },
  { id: 'cake', name: 'Cake', category: 'misc', tags: ['cake', 'frosting', 'layer', 'birthday', 'sweet', 'candle', 'dessert'], emoji: '🎂' },
  { id: 'cookie', name: 'Cookie', category: 'misc', tags: ['cookie', 'bake', 'chip', 'sweet', 'round', 'crumb', 'treat'], emoji: '🍪' },
  { id: 'candy', name: 'Candy', category: 'misc', tags: ['candy', 'sweet', 'sugar', 'wrap', 'treat', 'colorful', 'hard'], emoji: '🍬' },
  { id: 'chocolate', name: 'Chocolate', category: 'misc', tags: ['chocolate', 'cocoa', 'sweet', 'brown', 'bar', 'rich', 'melt'], emoji: '🍫' },
  { id: 'honey_jar', name: 'Honey Jar', category: 'misc', tags: ['honey', 'jar', 'golden', 'sweet', 'bee', 'drip', 'sticky'], emoji: '🍯' },
  { id: 'meat_leg', name: 'Leg of Meat', category: 'misc', tags: ['meat', 'leg', 'bone', 'roast', 'feast', 'hearty', 'cook'], emoji: '🍖' },
  { id: 'fish_cooked', name: 'Cooked Fish', category: 'misc', tags: ['fish', 'cooked', 'plate', 'meal', 'bone', 'sea', 'food'], emoji: '🐟' },
  { id: 'soup_bowl', name: 'Soup Bowl', category: 'misc', tags: ['soup', 'bowl', 'hot', 'steam', 'spoon', 'broth', 'warm'], emoji: '🍲' },
  { id: 'pizza_slice', name: 'Pizza Slice', category: 'misc', tags: ['pizza', 'slice', 'cheese', 'triangle', 'pepperoni', 'hot', 'food'], emoji: '🍕' },
  { id: 'sushi', name: 'Sushi', category: 'misc', tags: ['sushi', 'rice', 'fish', 'roll', 'japan', 'seaweed', 'fresh'], emoji: '🍣' },
  { id: 'ramen', name: 'Ramen', category: 'misc', tags: ['ramen', 'noodle', 'soup', 'hot', 'bowl', 'japan', 'steam'], emoji: '🍜' },
  { id: 'ice_cream', name: 'Ice Cream', category: 'misc', tags: ['ice', 'cream', 'cold', 'cone', 'scoop', 'sweet', 'vanilla'], emoji: '🍦' },
  { id: 'donut', name: 'Donut', category: 'misc', tags: ['donut', 'ring', 'frosting', 'sweet', 'sprinkle', 'hole', 'glaze'], emoji: '🍩' },
  { id: 'pretzel', name: 'Pretzel', category: 'misc', tags: ['pretzel', 'twist', 'salt', 'bake', 'knot', 'brown', 'snack'], emoji: '🥨' },
  { id: 'grape_bunch', name: 'Grape Bunch', category: 'misc', tags: ['grape', 'bunch', 'purple', 'vine', 'fruit', 'wine', 'cluster'], emoji: '🍇' },
  { id: 'cherry_fruit', name: 'Cherry', category: 'misc', tags: ['cherry', 'red', 'fruit', 'pair', 'stem', 'sweet', 'small'], emoji: '🍒' },
  { id: 'strawberry', name: 'Strawberry', category: 'misc', tags: ['strawberry', 'red', 'fruit', 'seed', 'sweet', 'berry', 'garden'], emoji: '🍓' },
  { id: 'pumpkin', name: 'Pumpkin', category: 'misc', tags: ['pumpkin', 'orange', 'halloween', 'carve', 'autumn', 'vine', 'large'], emoji: '🎃' },
  { id: 'carrot', name: 'Carrot', category: 'misc', tags: ['carrot', 'orange', 'root', 'vegetable', 'rabbit', 'garden', 'long'], emoji: '🥕' },
  { id: 'pepper_hot', name: 'Hot Pepper', category: 'misc', tags: ['pepper', 'hot', 'red', 'spicy', 'chili', 'fire', 'seed'], emoji: '🌶️' },
  { id: 'garlic', name: 'Garlic', category: 'misc', tags: ['garlic', 'bulb', 'clove', 'pungent', 'cook', 'vampire', 'white'], emoji: '🧄' },
  // Weapons & Combat
  { id: 'bomb', name: 'Bomb', category: 'misc', tags: ['bomb', 'explode', 'fuse', 'round', 'black', 'danger', 'boom'], emoji: '💣' },
  { id: 'dynamite', name: 'Dynamite', category: 'misc', tags: ['dynamite', 'explode', 'fuse', 'red', 'stick', 'blast', 'tnt'], emoji: '🧨' },
  { id: 'arrow', name: 'Arrow', category: 'misc', tags: ['arrow', 'bow', 'point', 'shoot', 'fly', 'quiver', 'feather'], emoji: '🏹' },
  { id: 'crossbow', name: 'Crossbow', category: 'misc', tags: ['crossbow', 'bolt', 'aim', 'trigger', 'weapon', 'medieval', 'hunt'], emoji: '🏹' },
  { id: 'dagger', name: 'Dagger', category: 'misc', tags: ['dagger', 'blade', 'short', 'sharp', 'stab', 'sneak', 'hilt'], emoji: '🗡️' },
  { id: 'rapier', name: 'Rapier', category: 'misc', tags: ['rapier', 'sword', 'thin', 'fence', 'thrust', 'elegant', 'guard'], emoji: '⚔️' },
  { id: 'mace_weapon', name: 'Mace', category: 'misc', tags: ['mace', 'weapon', 'heavy', 'spike', 'crush', 'metal', 'head'], emoji: '🔨' },
  { id: 'trident', name: 'Trident', category: 'misc', tags: ['trident', 'three', 'prong', 'sea', 'poseidon', 'spear', 'weapon'], emoji: '🔱' },
  { id: 'boomerang', name: 'Boomerang', category: 'misc', tags: ['boomerang', 'throw', 'return', 'curve', 'wood', 'australia', 'spin'], emoji: '🪃' },
  { id: 'shuriken', name: 'Shuriken', category: 'misc', tags: ['shuriken', 'star', 'throw', 'ninja', 'blade', 'metal', 'sharp'], emoji: '⭐' },
  // Games & Toys
  { id: 'dice', name: 'Dice', category: 'misc', tags: ['dice', 'roll', 'number', 'game', 'chance', 'cube', 'dot'], emoji: '🎲' },
  { id: 'playing_card', name: 'Playing Card', category: 'misc', tags: ['card', 'play', 'suit', 'ace', 'game', 'deck', 'spade'], emoji: '🃏' },
  { id: 'chess_piece', name: 'Chess Piece', category: 'misc', tags: ['chess', 'piece', 'king', 'game', 'strategy', 'board', 'move'], emoji: '♟️' },
  { id: 'puzzle_piece', name: 'Puzzle Piece', category: 'misc', tags: ['puzzle', 'piece', 'fit', 'connect', 'jigsaw', 'solve', 'shape'], emoji: '🧩' },
  { id: 'top_hat', name: 'Top Hat', category: 'misc', tags: ['top', 'hat', 'magic', 'gentleman', 'tall', 'black', 'formal'], emoji: '🎩' },
  { id: 'mask_masquerade', name: 'Masquerade Mask', category: 'misc', tags: ['mask', 'masquerade', 'party', 'eye', 'mystery', 'feather', 'ornate'], emoji: '🎭' },
  { id: 'puppet', name: 'Puppet', category: 'misc', tags: ['puppet', 'string', 'control', 'wooden', 'dance', 'show', 'figure'], emoji: '🎭' },
  { id: 'snow_globe', name: 'Snow Globe', category: 'misc', tags: ['snow', 'globe', 'shake', 'winter', 'scene', 'glass', 'sparkle'], emoji: '🔮' },
  { id: 'kaleidoscope', name: 'Kaleidoscope', category: 'misc', tags: ['kaleidoscope', 'color', 'pattern', 'turn', 'mirror', 'tube', 'beautiful'], emoji: '🌈' },
  { id: 'spinning_top', name: 'Spinning Top', category: 'misc', tags: ['spinning', 'top', 'spin', 'balance', 'toy', 'point', 'whirl'], emoji: '🌀' },
  { id: 'teddy_bear', name: 'Teddy Bear', category: 'misc', tags: ['teddy', 'bear', 'soft', 'toy', 'hug', 'plush', 'comfort'], emoji: '🧸' },
  { id: 'kite', name: 'Kite', category: 'misc', tags: ['kite', 'fly', 'wind', 'string', 'sky', 'tail', 'colorful'], emoji: '🪁' },
  { id: 'balloon', name: 'Balloon', category: 'misc', tags: ['balloon', 'float', 'air', 'pop', 'party', 'string', 'colorful'], emoji: '🎈' },
  { id: 'paper_crane', name: 'Paper Crane', category: 'misc', tags: ['paper', 'crane', 'origami', 'fold', 'wish', 'bird', 'japan'], emoji: '🕊️' },
  { id: 'yo_yo', name: 'Yo-Yo', category: 'misc', tags: ['yo-yo', 'spin', 'string', 'toy', 'trick', 'up', 'down'], emoji: '🪀' },
  { id: 'jack_in_box', name: 'Jack in the Box', category: 'misc', tags: ['jack', 'box', 'spring', 'surprise', 'crank', 'toy', 'pop'], emoji: '🤡' },
  // Symbols & Nature
  { id: 'snowflake', name: 'Snowflake', category: 'misc', tags: ['snowflake', 'ice', 'cold', 'winter', 'crystal', 'unique', 'white'], emoji: '❄️' },
  { id: 'sun_symbol', name: 'Sun', category: 'misc', tags: ['sun', 'bright', 'warm', 'day', 'ray', 'golden', 'shine'], emoji: '☀️' },
  { id: 'moon_symbol', name: 'Moon', category: 'misc', tags: ['moon', 'night', 'crescent', 'silver', 'glow', 'lunar', 'dark'], emoji: '🌙' },
  { id: 'star_symbol', name: 'Star', category: 'misc', tags: ['star', 'shine', 'night', 'point', 'bright', 'sky', 'wish'], emoji: '⭐' },
  { id: 'lightning_bolt', name: 'Lightning Bolt', category: 'misc', tags: ['lightning', 'bolt', 'electric', 'fast', 'strike', 'storm', 'power'], emoji: '⚡' },
  { id: 'cloud', name: 'Cloud', category: 'misc', tags: ['cloud', 'sky', 'white', 'fluffy', 'rain', 'float', 'weather'], emoji: '☁️' },
  { id: 'raindrop', name: 'Raindrop', category: 'misc', tags: ['rain', 'drop', 'water', 'blue', 'fall', 'tear', 'wet'], emoji: '💧' },
  { id: 'tornado', name: 'Tornado', category: 'misc', tags: ['tornado', 'wind', 'spin', 'storm', 'funnel', 'destroy', 'force'], emoji: '🌪️' },
  { id: 'rainbow', name: 'Rainbow', category: 'misc', tags: ['rainbow', 'color', 'arch', 'rain', 'sun', 'spectrum', 'hope'], emoji: '🌈' },
  { id: 'comet', name: 'Comet', category: 'misc', tags: ['comet', 'tail', 'sky', 'ice', 'glow', 'space', 'streak'], emoji: '☄️' },
  { id: 'planet', name: 'Planet', category: 'misc', tags: ['planet', 'sphere', 'orbit', 'ring', 'space', 'world', 'rotate'], emoji: '🪐' },
  { id: 'shooting_star', name: 'Shooting Star', category: 'misc', tags: ['shooting', 'star', 'wish', 'streak', 'night', 'glow', 'fast'], emoji: '🌠' },
  { id: 'horseshoe', name: 'Horseshoe', category: 'misc', tags: ['horseshoe', 'luck', 'iron', 'horse', 'shoe', 'hang', 'fortune'], emoji: '🧲' },
  { id: 'hobbyhorse', name: 'Hobbyhorse', category: 'misc', tags: ['hobbyhorse', 'stick', 'horse', 'toy', 'ride', 'play', 'child'], emoji: '🐴' },
  { id: 'rubber_duck', name: 'Rubber Duck', category: 'misc', tags: ['rubber', 'duck', 'yellow', 'bath', 'squeak', 'toy', 'float'], emoji: '🦆' },
  { id: 'pinwheel', name: 'Pinwheel', category: 'misc', tags: ['pinwheel', 'spin', 'wind', 'color', 'toy', 'blow', 'garden'], emoji: '🌀' },
  { id: 'magic_eight_ball', name: 'Magic 8 Ball', category: 'misc', tags: ['magic', 'eight', 'ball', 'fortune', 'shake', 'answer', 'black'], emoji: '🎱' },
  { id: 'toy_soldier', name: 'Toy Soldier', category: 'misc', tags: ['toy', 'soldier', 'tin', 'march', 'uniform', 'red', 'stand'], emoji: '💂' },
];
