// Nature category sprites — animals, plants, minerals, sea life, insects, birds
export const NATURE_SPRITES = [
  { id: 'amethyst', name: 'Amethyst', category: 'nature', tags: ['amethyst', 'gem', 'crystal', 'purple', 'stone', 'mineral', 'jewel', 'quartz'], emoji: '💎' },
  // Animals
  { id: 'wolf', name: 'Wolf', category: 'nature', tags: ['wolf', 'howl', 'pack', 'wild', 'predator', 'grey', 'canine'], emoji: '🐺' },
  { id: 'fox', name: 'Fox', category: 'nature', tags: ['fox', 'cunning', 'red', 'tail', 'sly', 'wild', 'forest'], emoji: '🦊' },
  { id: 'deer', name: 'Deer', category: 'nature', tags: ['deer', 'antler', 'forest', 'graceful', 'stag', 'doe', 'gentle'], emoji: '🦌' },
  { id: 'bear', name: 'Bear', category: 'nature', tags: ['bear', 'strong', 'brown', 'wild', 'claw', 'hibernate', 'fierce'], emoji: '🐻' },
  { id: 'rabbit', name: 'Rabbit', category: 'nature', tags: ['rabbit', 'bunny', 'hop', 'ear', 'fur', 'fast', 'burrow'], emoji: '🐇' },
  { id: 'cat_animal', name: 'Cat', category: 'nature', tags: ['cat', 'feline', 'purr', 'whisker', 'paw', 'agile', 'sleek'], emoji: '🐱' },
  { id: 'horse', name: 'Horse', category: 'nature', tags: ['horse', 'gallop', 'mane', 'ride', 'stable', 'hoof', 'noble'], emoji: '🐴' },
  { id: 'elephant', name: 'Elephant', category: 'nature', tags: ['elephant', 'trunk', 'tusk', 'large', 'memory', 'grey', 'wise'], emoji: '🐘' },
  { id: 'lion', name: 'Lion', category: 'nature', tags: ['lion', 'mane', 'roar', 'king', 'pride', 'golden', 'fierce'], emoji: '🦁' },
  { id: 'tiger', name: 'Tiger', category: 'nature', tags: ['tiger', 'stripe', 'fierce', 'orange', 'predator', 'jungle', 'power'], emoji: '🐯' },
  { id: 'whale', name: 'Whale', category: 'nature', tags: ['whale', 'ocean', 'deep', 'large', 'blue', 'swim', 'spout'], emoji: '🐋' },
  { id: 'dolphin', name: 'Dolphin', category: 'nature', tags: ['dolphin', 'swim', 'ocean', 'playful', 'smart', 'leap', 'grey'], emoji: '🐬' },
  { id: 'shark', name: 'Shark', category: 'nature', tags: ['shark', 'fin', 'teeth', 'ocean', 'predator', 'danger', 'fast'], emoji: '🦈' },
  { id: 'octopus', name: 'Octopus', category: 'nature', tags: ['octopus', 'tentacle', 'ink', 'ocean', 'eight', 'smart', 'deep'], emoji: '🐙' },
  { id: 'turtle', name: 'Turtle', category: 'nature', tags: ['turtle', 'shell', 'slow', 'wise', 'swim', 'ancient', 'green'], emoji: '🐢' },
  { id: 'frog', name: 'Frog', category: 'nature', tags: ['frog', 'leap', 'pond', 'green', 'croak', 'amphibian', 'lily'], emoji: '🐸' },
  { id: 'snake', name: 'Snake', category: 'nature', tags: ['snake', 'slither', 'scale', 'venom', 'coil', 'reptile', 'fang'], emoji: '🐍' },
  { id: 'lizard', name: 'Lizard', category: 'nature', tags: ['lizard', 'scale', 'reptile', 'tail', 'sun', 'crawl', 'gecko'], emoji: '🦎' },
  { id: 'bat', name: 'Bat', category: 'nature', tags: ['bat', 'wing', 'night', 'fly', 'cave', 'sonar', 'dark'], emoji: '🦇' },
  { id: 'monkey', name: 'Monkey', category: 'nature', tags: ['monkey', 'climb', 'tail', 'playful', 'banana', 'jungle', 'swing'], emoji: '🐒' },
  // Birds
  { id: 'eagle', name: 'Eagle', category: 'nature', tags: ['eagle', 'soar', 'talon', 'majestic', 'sky', 'hunt', 'bald'], emoji: '🦅' },
  { id: 'hawk', name: 'Hawk', category: 'nature', tags: ['hawk', 'hunt', 'keen', 'raptor', 'fly', 'prey', 'sharp'], emoji: '🦅' },
  { id: 'raven', name: 'Raven', category: 'nature', tags: ['raven', 'crow', 'black', 'dark', 'omen', 'clever', 'feather'], emoji: '🐦‍⬛' },
  { id: 'dove', name: 'Dove', category: 'nature', tags: ['dove', 'peace', 'white', 'gentle', 'fly', 'olive', 'pure'], emoji: '🕊️' },
  { id: 'parrot', name: 'Parrot', category: 'nature', tags: ['parrot', 'colorful', 'talk', 'tropical', 'beak', 'mimic', 'bright'], emoji: '🦜' },
  { id: 'peacock', name: 'Peacock', category: 'nature', tags: ['peacock', 'feather', 'display', 'blue', 'green', 'beautiful', 'tail'], emoji: '🦚' },
  { id: 'swan', name: 'Swan', category: 'nature', tags: ['swan', 'graceful', 'white', 'lake', 'elegant', 'neck', 'glide'], emoji: '🦢' },
  { id: 'penguin', name: 'Penguin', category: 'nature', tags: ['penguin', 'ice', 'waddle', 'black', 'white', 'arctic', 'cold'], emoji: '🐧' },
  { id: 'phoenix_bird', name: 'Phoenix', category: 'nature', tags: ['phoenix', 'fire', 'rebirth', 'flame', 'ash', 'rise', 'immortal'], emoji: '🔥' },
  { id: 'hummingbird', name: 'Hummingbird', category: 'nature', tags: ['hummingbird', 'tiny', 'fast', 'hover', 'nectar', 'iridescent', 'wing'], emoji: '🐦' },
  // Insects
  { id: 'butterfly', name: 'Butterfly', category: 'nature', tags: ['butterfly', 'wing', 'colorful', 'flutter', 'transform', 'garden', 'delicate'], emoji: '🦋' },
  { id: 'bee', name: 'Bee', category: 'nature', tags: ['bee', 'honey', 'buzz', 'sting', 'hive', 'pollen', 'yellow'], emoji: '🐝' },
  { id: 'spider', name: 'Spider', category: 'nature', tags: ['spider', 'web', 'spin', 'eight', 'leg', 'silk', 'trap'], emoji: '🕷️' },
  { id: 'beetle', name: 'Beetle', category: 'nature', tags: ['beetle', 'bug', 'shell', 'crawl', 'armor', 'horn', 'insect'], emoji: '🪲' },
  { id: 'dragonfly', name: 'Dragonfly', category: 'nature', tags: ['dragonfly', 'wing', 'hover', 'pond', 'iridescent', 'fast', 'summer'], emoji: '🪰' },
  { id: 'firefly', name: 'Firefly', category: 'nature', tags: ['firefly', 'glow', 'night', 'light', 'blink', 'summer', 'warm'], emoji: '✨' },
  // Sea life
  { id: 'crab', name: 'Crab', category: 'nature', tags: ['crab', 'claw', 'shell', 'beach', 'pinch', 'sideways', 'red'], emoji: '🦀' },
  { id: 'jellyfish', name: 'Jellyfish', category: 'nature', tags: ['jellyfish', 'tentacle', 'sting', 'glow', 'float', 'ocean', 'transparent'], emoji: '🪼' },
  { id: 'starfish', name: 'Starfish', category: 'nature', tags: ['starfish', 'star', 'ocean', 'five', 'arm', 'beach', 'tide'], emoji: '⭐' },
  { id: 'seahorse', name: 'Seahorse', category: 'nature', tags: ['seahorse', 'ocean', 'tiny', 'curl', 'swim', 'reef', 'gentle'], emoji: '🐴' },
  { id: 'shell', name: 'Shell', category: 'nature', tags: ['shell', 'sea', 'beach', 'spiral', 'conch', 'ocean', 'pearl'], emoji: '🐚' },
  // Plants
  { id: 'oak_tree', name: 'Oak Tree', category: 'nature', tags: ['oak', 'tree', 'leaf', 'trunk', 'branch', 'tall', 'ancient'], emoji: '🌳' },
  { id: 'mushroom', name: 'Mushroom', category: 'nature', tags: ['mushroom', 'fungus', 'cap', 'forest', 'red', 'spot', 'grow'], emoji: '🍄' },
  { id: 'flower', name: 'Flower', category: 'nature', tags: ['flower', 'petal', 'bloom', 'garden', 'colorful', 'scent', 'spring'], emoji: '🌸' },
  { id: 'rose', name: 'Rose', category: 'nature', tags: ['rose', 'red', 'thorn', 'love', 'petal', 'bloom', 'garden'], emoji: '🌹' },
  { id: 'sunflower', name: 'Sunflower', category: 'nature', tags: ['sunflower', 'sun', 'yellow', 'tall', 'seed', 'bright', 'field'], emoji: '🌻' },
  { id: 'cactus', name: 'Cactus', category: 'nature', tags: ['cactus', 'desert', 'spine', 'green', 'dry', 'succulent', 'tough'], emoji: '🌵' },
  { id: 'fern', name: 'Fern', category: 'nature', tags: ['fern', 'leaf', 'green', 'forest', 'frond', 'shade', 'ancient'], emoji: '🌿' },
  { id: 'ivy', name: 'Ivy', category: 'nature', tags: ['ivy', 'vine', 'climb', 'green', 'wall', 'leaf', 'grow'], emoji: '🌿' },
  { id: 'seaweed', name: 'Seaweed', category: 'nature', tags: ['seaweed', 'ocean', 'green', 'kelp', 'wave', 'underwater', 'plant'], emoji: '🌊' },
  { id: 'coral', name: 'Coral', category: 'nature', tags: ['coral', 'reef', 'ocean', 'colorful', 'branch', 'tropical', 'sea'], emoji: '🪸' },
  { id: 'lotus', name: 'Lotus', category: 'nature', tags: ['lotus', 'flower', 'water', 'pink', 'pure', 'zen', 'pond'], emoji: '🪷' },
  { id: 'cherry_blossom', name: 'Cherry Blossom', category: 'nature', tags: ['cherry', 'blossom', 'pink', 'spring', 'petal', 'tree', 'japan'], emoji: '🌸' },
  { id: 'clover', name: 'Clover', category: 'nature', tags: ['clover', 'lucky', 'green', 'leaf', 'four', 'field', 'irish'], emoji: '🍀' },
  { id: 'vine', name: 'Vine', category: 'nature', tags: ['vine', 'climb', 'green', 'twist', 'grape', 'tendril', 'grow'], emoji: '🌿' },
  { id: 'bamboo', name: 'Bamboo', category: 'nature', tags: ['bamboo', 'tall', 'green', 'hollow', 'strong', 'asia', 'panda'], emoji: '🎋' },
  // Natural elements
  { id: 'leaf', name: 'Leaf', category: 'nature', tags: ['leaf', 'green', 'fall', 'tree', 'autumn', 'vein', 'nature'], emoji: '🍃' },
  { id: 'acorn', name: 'Acorn', category: 'nature', tags: ['acorn', 'oak', 'seed', 'nut', 'squirrel', 'fall', 'small'], emoji: '🌰' },
  { id: 'feather', name: 'Feather', category: 'nature', tags: ['feather', 'bird', 'light', 'float', 'quill', 'soft', 'fly'], emoji: '🪶' },
  { id: 'nest', name: 'Nest', category: 'nature', tags: ['nest', 'bird', 'egg', 'twig', 'home', 'branch', 'safe'], emoji: '🪹' },
  { id: 'egg', name: 'Egg', category: 'nature', tags: ['egg', 'oval', 'shell', 'hatch', 'bird', 'life', 'fragile'], emoji: '🥚' },
  { id: 'bone', name: 'Bone', category: 'nature', tags: ['bone', 'skeleton', 'fossil', 'white', 'marrow', 'ancient', 'remain'], emoji: '🦴' },
  { id: 'fossil', name: 'Fossil', category: 'nature', tags: ['fossil', 'ancient', 'stone', 'imprint', 'dinosaur', 'old', 'preserve'], emoji: '🦕' },
  { id: 'driftwood', name: 'Driftwood', category: 'nature', tags: ['driftwood', 'wood', 'beach', 'sea', 'weathered', 'smooth', 'float'], emoji: '🪵' },
  { id: 'pebble', name: 'Pebble', category: 'nature', tags: ['pebble', 'stone', 'small', 'smooth', 'river', 'round', 'skip'], emoji: '🪨' },
  { id: 'root', name: 'Root', category: 'nature', tags: ['root', 'tree', 'ground', 'deep', 'twist', 'earth', 'anchor'], emoji: '🌱' },
  // Minerals & Gems
  { id: 'jade', name: 'Jade', category: 'nature', tags: ['jade', 'green', 'stone', 'smooth', 'carved', 'precious', 'asian'], emoji: '🟢' },
  { id: 'sapphire', name: 'Sapphire', category: 'nature', tags: ['sapphire', 'blue', 'gem', 'precious', 'brilliant', 'facet', 'royal'], emoji: '💙' },
  { id: 'ruby', name: 'Ruby', category: 'nature', tags: ['ruby', 'red', 'gem', 'precious', 'brilliant', 'facet', 'blood'], emoji: '❤️' },
  { id: 'emerald', name: 'Emerald', category: 'nature', tags: ['emerald', 'green', 'gem', 'precious', 'brilliant', 'facet', 'lush'], emoji: '💚' },
  { id: 'diamond', name: 'Diamond', category: 'nature', tags: ['diamond', 'clear', 'gem', 'hard', 'brilliant', 'sparkle', 'facet'], emoji: '💎' },
  { id: 'topaz', name: 'Topaz', category: 'nature', tags: ['topaz', 'yellow', 'gem', 'warm', 'golden', 'facet', 'bright'], emoji: '💛' },
  { id: 'opal', name: 'Opal', category: 'nature', tags: ['opal', 'iridescent', 'gem', 'rainbow', 'shimmer', 'white', 'fire'], emoji: '🤍' },
  { id: 'pearl', name: 'Pearl', category: 'nature', tags: ['pearl', 'white', 'round', 'oyster', 'ocean', 'lustrous', 'smooth'], emoji: '⚪' },
  { id: 'moonstone', name: 'Moonstone', category: 'nature', tags: ['moonstone', 'moon', 'glow', 'pale', 'ethereal', 'gem', 'night'], emoji: '🌙' },
  { id: 'amber', name: 'Amber', category: 'nature', tags: ['amber', 'golden', 'resin', 'ancient', 'insect', 'warm', 'fossil'], emoji: '🟠' },
  { id: 'obsidian', name: 'Obsidian', category: 'nature', tags: ['obsidian', 'black', 'glass', 'volcanic', 'sharp', 'dark', 'smooth'], emoji: '⚫' },
  { id: 'geode', name: 'Geode', category: 'nature', tags: ['geode', 'crystal', 'rock', 'hollow', 'sparkle', 'purple', 'hidden'], emoji: '🪨' },
  { id: 'quartz', name: 'Quartz', category: 'nature', tags: ['quartz', 'crystal', 'clear', 'point', 'mineral', 'prism', 'energy'], emoji: '🔮' },
  { id: 'garnet', name: 'Garnet', category: 'nature', tags: ['garnet', 'red', 'gem', 'deep', 'facet', 'dark', 'wine'], emoji: '🔴' },
  { id: 'turquoise', name: 'Turquoise', category: 'nature', tags: ['turquoise', 'blue', 'green', 'stone', 'native', 'sky', 'copper'], emoji: '🩵' },
  { id: 'lapis_lazuli', name: 'Lapis Lazuli', category: 'nature', tags: ['lapis', 'lazuli', 'blue', 'gold', 'fleck', 'ancient', 'deep'], emoji: '🔵' },
  { id: 'citrine', name: 'Citrine', category: 'nature', tags: ['citrine', 'yellow', 'gem', 'sunny', 'warm', 'golden', 'bright'], emoji: '💛' },
  { id: 'onyx', name: 'Onyx', category: 'nature', tags: ['onyx', 'black', 'gem', 'smooth', 'polished', 'dark', 'band'], emoji: '⚫' },
];
