// Treasures category sprites — jewelry, coins, artifacts, relics, precious objects
export const TREASURE_SPRITES = [
  { id: 'chest', name: 'Treasure Chest', category: 'treasures', tags: ['treasure', 'chest', 'gold', 'pirate', 'loot', 'box', 'wooden', 'lock', 'hidden'], emoji: '📦' },
  { id: 'gold_coin', name: 'Gold Coin', category: 'treasures', tags: ['gold', 'coin', 'money', 'round', 'shine', 'treasure', 'stack'], emoji: '🪙' },
  { id: 'silver_coin', name: 'Silver Coin', category: 'treasures', tags: ['silver', 'coin', 'money', 'round', 'shine', 'treasure', 'mint'], emoji: '🪙' },
  { id: 'copper_coin', name: 'Copper Coin', category: 'treasures', tags: ['copper', 'coin', 'money', 'round', 'penny', 'old', 'patina'], emoji: '🪙' },
  { id: 'gold_bar', name: 'Gold Bar', category: 'treasures', tags: ['gold', 'bar', 'ingot', 'heavy', 'bullion', 'wealth', 'shine'], emoji: '🥇' },
  { id: 'gold_nugget', name: 'Gold Nugget', category: 'treasures', tags: ['gold', 'nugget', 'raw', 'mine', 'rough', 'prospect', 'natural'], emoji: '✨' },
  { id: 'treasure_map', name: 'Treasure Map', category: 'treasures', tags: ['treasure', 'map', 'pirate', 'x', 'route', 'island', 'secret'], emoji: '🗺️' },
  { id: 'crown_royal', name: 'Royal Crown', category: 'treasures', tags: ['crown', 'royal', 'king', 'queen', 'gold', 'gem', 'rule'], emoji: '👑' },
  { id: 'tiara', name: 'Tiara', category: 'treasures', tags: ['tiara', 'princess', 'gem', 'silver', 'elegant', 'sparkle', 'head'], emoji: '👑' },
  { id: 'diadem', name: 'Diadem', category: 'treasures', tags: ['diadem', 'crown', 'circle', 'jewel', 'head', 'noble', 'ancient'], emoji: '👑' },
  { id: 'scepter_royal', name: 'Royal Scepter', category: 'treasures', tags: ['scepter', 'royal', 'gold', 'gem', 'rule', 'orb', 'king'], emoji: '🏆' },
  { id: 'orb_royal', name: 'Royal Orb', category: 'treasures', tags: ['orb', 'royal', 'gold', 'cross', 'sphere', 'rule', 'power'], emoji: '🔮' },
  { id: 'chalice', name: 'Chalice', category: 'treasures', tags: ['chalice', 'cup', 'gold', 'drink', 'wine', 'holy', 'stem'], emoji: '🏆' },
  { id: 'goblet', name: 'Goblet', category: 'treasures', tags: ['goblet', 'cup', 'drink', 'wine', 'stem', 'metal', 'feast'], emoji: '🍷' },
  { id: 'grail', name: 'Grail', category: 'treasures', tags: ['grail', 'holy', 'cup', 'quest', 'sacred', 'golden', 'legend'], emoji: '🏆' },
  { id: 'necklace', name: 'Necklace', category: 'treasures', tags: ['necklace', 'chain', 'gem', 'neck', 'jewelry', 'pendant', 'elegant'], emoji: '📿' },
  { id: 'bracelet', name: 'Bracelet', category: 'treasures', tags: ['bracelet', 'wrist', 'band', 'jewelry', 'gold', 'charm', 'clasp'], emoji: '📿' },
  { id: 'brooch', name: 'Brooch', category: 'treasures', tags: ['brooch', 'pin', 'gem', 'clasp', 'ornate', 'vintage', 'jewel'], emoji: '💎' },
  { id: 'earring', name: 'Earring', category: 'treasures', tags: ['earring', 'ear', 'dangle', 'gem', 'jewelry', 'gold', 'stud'], emoji: '💎' },
  { id: 'pendant', name: 'Pendant', category: 'treasures', tags: ['pendant', 'necklace', 'hang', 'gem', 'chain', 'jewelry', 'tear'], emoji: '📿' },
  { id: 'locket', name: 'Locket', category: 'treasures', tags: ['locket', 'open', 'photo', 'heart', 'chain', 'secret', 'gold'], emoji: '💛' },
  { id: 'signet_ring', name: 'Signet Ring', category: 'treasures', tags: ['signet', 'ring', 'seal', 'crest', 'stamp', 'gold', 'noble'], emoji: '💍' },
  { id: 'wedding_ring', name: 'Wedding Ring', category: 'treasures', tags: ['wedding', 'ring', 'band', 'gold', 'love', 'marriage', 'simple'], emoji: '💍' },
  { id: 'anklet', name: 'Anklet', category: 'treasures', tags: ['anklet', 'ankle', 'chain', 'jewelry', 'delicate', 'gold', 'charm'], emoji: '📿' },
  { id: 'choker', name: 'Choker', category: 'treasures', tags: ['choker', 'neck', 'close', 'velvet', 'gem', 'band', 'elegant'], emoji: '📿' },
  { id: 'jewel_box', name: 'Jewel Box', category: 'treasures', tags: ['jewel', 'box', 'velvet', 'store', 'ornate', 'wooden', 'clasp'], emoji: '💍' },
  { id: 'faberge_egg', name: 'Fabergé Egg', category: 'treasures', tags: ['faberge', 'egg', 'ornate', 'jewel', 'enamel', 'russian', 'precious'], emoji: '🥚' },
  { id: 'statuette', name: 'Statuette', category: 'treasures', tags: ['statuette', 'small', 'figure', 'gold', 'bronze', 'sculpture', 'art'], emoji: '🗿' },
  { id: 'figurine', name: 'Figurine', category: 'treasures', tags: ['figurine', 'small', 'porcelain', 'delicate', 'collect', 'display', 'craft'], emoji: '🎎' },
  { id: 'idol', name: 'Idol', category: 'treasures', tags: ['idol', 'gold', 'ancient', 'temple', 'worship', 'figure', 'relic'], emoji: '🗿' },
  { id: 'mask_ceremonial', name: 'Ceremonial Mask', category: 'treasures', tags: ['mask', 'ceremonial', 'gold', 'face', 'ritual', 'tribal', 'ornate'], emoji: '🎭' },
  { id: 'scarab', name: 'Scarab', category: 'treasures', tags: ['scarab', 'beetle', 'egypt', 'gold', 'amulet', 'ancient', 'carved'], emoji: '🪲' },
  { id: 'ankh', name: 'Ankh', category: 'treasures', tags: ['ankh', 'life', 'egypt', 'cross', 'loop', 'symbol', 'ancient', 'gold'], emoji: '☥' },
  { id: 'eye_of_horus', name: 'Eye of Horus', category: 'treasures', tags: ['eye', 'horus', 'egypt', 'protect', 'ancient', 'symbol', 'gold'], emoji: '👁️' },
  { id: 'jade_dragon', name: 'Jade Dragon', category: 'treasures', tags: ['jade', 'dragon', 'carved', 'green', 'asian', 'ornate', 'precious'], emoji: '🐉' },
  { id: 'golden_fleece', name: 'Golden Fleece', category: 'treasures', tags: ['golden', 'fleece', 'wool', 'ram', 'greek', 'quest', 'mythology'], emoji: '🐏' },
  { id: 'philosophers_stone', name: "Philosopher's Stone", category: 'treasures', tags: ['philosopher', 'stone', 'alchemy', 'gold', 'transform', 'red', 'elixir'], emoji: '🔴' },
  { id: 'excalibur', name: 'Excalibur', category: 'treasures', tags: ['excalibur', 'sword', 'king', 'arthur', 'stone', 'legend', 'blade'], emoji: '⚔️' },
  { id: 'crystal_skull_artifact', name: 'Crystal Skull', category: 'treasures', tags: ['crystal', 'skull', 'clear', 'ancient', 'mystery', 'carved', 'artifact'], emoji: '💀' },
  { id: 'royal_seal', name: 'Royal Seal', category: 'treasures', tags: ['royal', 'seal', 'stamp', 'wax', 'crest', 'official', 'emblem'], emoji: '🔏' },
  { id: 'coat_of_arms', name: 'Coat of Arms', category: 'treasures', tags: ['coat', 'arms', 'heraldry', 'shield', 'crest', 'family', 'noble'], emoji: '🛡️' },
  { id: 'heirloom', name: 'Heirloom', category: 'treasures', tags: ['heirloom', 'family', 'old', 'pass', 'precious', 'antique', 'cherish'], emoji: '🏺' },
  { id: 'antique_clock', name: 'Antique Clock', category: 'treasures', tags: ['antique', 'clock', 'old', 'ornate', 'tick', 'brass', 'mantle'], emoji: '🕰️' },
  { id: 'ruby_ring', name: 'Ruby Ring', category: 'treasures', tags: ['ruby', 'ring', 'red', 'gold', 'gem', 'finger', 'sparkle'], emoji: '💍' },
  { id: 'emerald_necklace', name: 'Emerald Necklace', category: 'treasures', tags: ['emerald', 'necklace', 'green', 'gold', 'chain', 'gem', 'elegant'], emoji: '📿' },
  { id: 'sapphire_crown', name: 'Sapphire Crown', category: 'treasures', tags: ['sapphire', 'crown', 'blue', 'gold', 'royal', 'gem', 'regal'], emoji: '👑' },
  { id: 'diamond_tiara', name: 'Diamond Tiara', category: 'treasures', tags: ['diamond', 'tiara', 'sparkle', 'clear', 'princess', 'gem', 'brilliant'], emoji: '👑' },
  { id: 'pearl_strand', name: 'Pearl Strand', category: 'treasures', tags: ['pearl', 'strand', 'white', 'round', 'necklace', 'elegant', 'classic'], emoji: '📿' },
  { id: 'golden_chalice', name: 'Golden Chalice', category: 'treasures', tags: ['golden', 'chalice', 'cup', 'drink', 'ornate', 'holy', 'rim'], emoji: '🏆' },
  { id: 'silver_mirror', name: 'Silver Mirror', category: 'treasures', tags: ['silver', 'mirror', 'reflect', 'hand', 'ornate', 'frame', 'vanity'], emoji: '🪞' },
  { id: 'bronze_statue', name: 'Bronze Statue', category: 'treasures', tags: ['bronze', 'statue', 'figure', 'cast', 'patina', 'art', 'solid'], emoji: '🗿' },
  { id: 'ivory_comb', name: 'Ivory Comb', category: 'treasures', tags: ['ivory', 'comb', 'carved', 'teeth', 'ornate', 'ancient', 'delicate'], emoji: '💇' },
  { id: 'silk_tapestry', name: 'Silk Tapestry', category: 'treasures', tags: ['silk', 'tapestry', 'weave', 'color', 'scene', 'wall', 'thread'], emoji: '🧵' },
  { id: 'golden_harp', name: 'Golden Harp', category: 'treasures', tags: ['golden', 'harp', 'string', 'music', 'ornate', 'angel', 'melody'], emoji: '🎵' },
  { id: 'jeweled_dagger', name: 'Jeweled Dagger', category: 'treasures', tags: ['jeweled', 'dagger', 'gem', 'blade', 'ornate', 'gold', 'sharp'], emoji: '🗡️' },
  { id: 'ornate_box', name: 'Ornate Box', category: 'treasures', tags: ['ornate', 'box', 'carved', 'inlay', 'wooden', 'treasure', 'store'], emoji: '📦' },
  { id: 'music_box_ornate', name: 'Ornate Music Box', category: 'treasures', tags: ['music', 'box', 'ornate', 'melody', 'dancer', 'wind', 'trinket'], emoji: '🎶' },
  { id: 'gilded_frame', name: 'Gilded Frame', category: 'treasures', tags: ['gilded', 'frame', 'gold', 'picture', 'ornate', 'art', 'hang'], emoji: '🖼️' },
  { id: 'porcelain_vase', name: 'Porcelain Vase', category: 'treasures', tags: ['porcelain', 'vase', 'china', 'painted', 'delicate', 'blue', 'white'], emoji: '🏺' },
  { id: 'crystal_chandelier', name: 'Crystal Chandelier', category: 'treasures', tags: ['crystal', 'chandelier', 'hang', 'sparkle', 'light', 'prism', 'elegant'], emoji: '✨' },
  { id: 'silver_candelabra', name: 'Silver Candelabra', category: 'treasures', tags: ['silver', 'candelabra', 'candle', 'branch', 'elegant', 'shine', 'tall'], emoji: '🕯️' },
  { id: 'golden_compass', name: 'Golden Compass', category: 'treasures', tags: ['golden', 'compass', 'navigate', 'truth', 'pointer', 'ornate', 'device'], emoji: '🧭' },
  { id: 'marble_bust', name: 'Marble Bust', category: 'treasures', tags: ['marble', 'bust', 'sculpt', 'white', 'head', 'classical', 'roman'], emoji: '🗿' },
  { id: 'amber_necklace', name: 'Amber Necklace', category: 'treasures', tags: ['amber', 'necklace', 'golden', 'warm', 'bead', 'ancient', 'chain'], emoji: '📿' },
  { id: 'platinum_ring', name: 'Platinum Ring', category: 'treasures', tags: ['platinum', 'ring', 'silver', 'band', 'precious', 'smooth', 'rare'], emoji: '💍' },
  { id: 'obsidian_mirror', name: 'Obsidian Mirror', category: 'treasures', tags: ['obsidian', 'mirror', 'black', 'polished', 'aztec', 'dark', 'see'], emoji: '🪞' },
  { id: 'jade_pendant', name: 'Jade Pendant', category: 'treasures', tags: ['jade', 'pendant', 'green', 'carved', 'hang', 'chain', 'smooth'], emoji: '📿' },
  { id: 'turquoise_bracelet', name: 'Turquoise Bracelet', category: 'treasures', tags: ['turquoise', 'bracelet', 'blue', 'stone', 'wrist', 'native', 'silver'], emoji: '📿' },
  { id: 'garnet_brooch', name: 'Garnet Brooch', category: 'treasures', tags: ['garnet', 'brooch', 'red', 'pin', 'ornate', 'vintage', 'dark'], emoji: '💎' },
  { id: 'moonstone_ring', name: 'Moonstone Ring', category: 'treasures', tags: ['moonstone', 'ring', 'glow', 'pale', 'silver', 'ethereal', 'band'], emoji: '💍' },
  { id: 'opal_pendant', name: 'Opal Pendant', category: 'treasures', tags: ['opal', 'pendant', 'iridescent', 'shimmer', 'chain', 'fire', 'rainbow'], emoji: '📿' },
  { id: 'onyx_ring', name: 'Onyx Ring', category: 'treasures', tags: ['onyx', 'ring', 'black', 'polished', 'band', 'sleek', 'dark'], emoji: '💍' },
  { id: 'citrine_earring', name: 'Citrine Earring', category: 'treasures', tags: ['citrine', 'earring', 'yellow', 'drop', 'gold', 'sparkle', 'sun'], emoji: '💎' },
  { id: 'topaz_crown', name: 'Topaz Crown', category: 'treasures', tags: ['topaz', 'crown', 'yellow', 'gold', 'warm', 'gem', 'royal'], emoji: '👑' },
  { id: 'lapis_pendant', name: 'Lapis Pendant', category: 'treasures', tags: ['lapis', 'pendant', 'blue', 'gold', 'fleck', 'deep', 'hang'], emoji: '📿' },
  { id: 'coral_necklace', name: 'Coral Necklace', category: 'treasures', tags: ['coral', 'necklace', 'red', 'bead', 'sea', 'branch', 'natural'], emoji: '📿' },
  { id: 'mother_of_pearl', name: 'Mother of Pearl', category: 'treasures', tags: ['mother', 'pearl', 'shell', 'iridescent', 'smooth', 'inlay', 'shimmer'], emoji: '🐚' },
  { id: 'golden_apple', name: 'Golden Apple', category: 'treasures', tags: ['golden', 'apple', 'fruit', 'discord', 'myth', 'rare', 'shine'], emoji: '🍎' },
  { id: 'silver_arrow', name: 'Silver Arrow', category: 'treasures', tags: ['silver', 'arrow', 'point', 'fly', 'werewolf', 'pure', 'gleam'], emoji: '🏹' },
  { id: 'enchanted_mirror', name: 'Enchanted Mirror', category: 'treasures', tags: ['enchanted', 'mirror', 'magic', 'ornate', 'gold', 'see', 'truth'], emoji: '🪞' },
  { id: 'treasure_key', name: 'Treasure Key', category: 'treasures', tags: ['treasure', 'key', 'ornate', 'old', 'lock', 'skeleton', 'brass'], emoji: '🗝️' },
  { id: 'pirates_compass', name: "Pirate's Compass", category: 'treasures', tags: ['pirate', 'compass', 'sea', 'navigate', 'brass', 'old', 'voyage'], emoji: '🧭' },
  { id: 'sunken_relic', name: 'Sunken Relic', category: 'treasures', tags: ['sunken', 'relic', 'sea', 'old', 'barnacle', 'deep', 'ancient'], emoji: '🏺' },
  { id: 'ancient_coin', name: 'Ancient Coin', category: 'treasures', tags: ['ancient', 'coin', 'old', 'worn', 'face', 'bronze', 'rare'], emoji: '🪙' },
];
